// Code generated by protoc-gen-go. DO NOT EDIT.
// source: _proto/blimp/auth/v0/auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// BlimpAuth should provide all credentials necessary for authentication and
// authorization.
type BlimpAuth struct {
	// token is an OAuth ID token obtained via the blimp login-proxy.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// cluster_auth is a secret token authorizing use of the cluster. This is only
	// needed by some clusters.
	ClusterAuth          string   `protobuf:"bytes,2,opt,name=cluster_auth,json=clusterAuth,proto3" json:"cluster_auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlimpAuth) Reset()         { *m = BlimpAuth{} }
func (m *BlimpAuth) String() string { return proto.CompactTextString(m) }
func (*BlimpAuth) ProtoMessage()    {}
func (*BlimpAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a76ffd47462628a, []int{0}
}

func (m *BlimpAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlimpAuth.Unmarshal(m, b)
}
func (m *BlimpAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlimpAuth.Marshal(b, m, deterministic)
}
func (m *BlimpAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlimpAuth.Merge(m, src)
}
func (m *BlimpAuth) XXX_Size() int {
	return xxx_messageInfo_BlimpAuth.Size(m)
}
func (m *BlimpAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_BlimpAuth.DiscardUnknown(m)
}

var xxx_messageInfo_BlimpAuth proto.InternalMessageInfo

func (m *BlimpAuth) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *BlimpAuth) GetClusterAuth() string {
	if m != nil {
		return m.ClusterAuth
	}
	return ""
}

func init() {
	proto.RegisterType((*BlimpAuth)(nil), "blimp.auth.v0.BlimpAuth")
}

func init() {
	proto.RegisterFile("_proto/blimp/auth/v0/auth.proto", fileDescriptor_8a76ffd47462628a)
}

var fileDescriptor_8a76ffd47462628a = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x8f, 0x2f, 0x28, 0xca,
	0x2f, 0xc9, 0xd7, 0x4f, 0xca, 0xc9, 0xcc, 0x2d, 0xd0, 0x4f, 0x2c, 0x2d, 0xc9, 0xd0, 0x2f, 0x33,
	0x00, 0xd3, 0x7a, 0x60, 0x09, 0x21, 0x5e, 0xb0, 0x8c, 0x1e, 0x58, 0xa4, 0xcc, 0x40, 0xc9, 0x85,
	0x8b, 0xd3, 0x09, 0x24, 0xe0, 0x58, 0x5a, 0x92, 0x21, 0x24, 0xc2, 0xc5, 0x5a, 0x92, 0x9f, 0x9d,
	0x9a, 0x27, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x08, 0x29, 0x72, 0xf1, 0x24, 0xe7,
	0x94, 0x16, 0x97, 0xa4, 0x16, 0xc5, 0x83, 0x74, 0x49, 0x30, 0x81, 0x25, 0xb9, 0xa1, 0x62, 0x20,
	0x8d, 0x4e, 0xea, 0x51, 0xaa, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa,
	0xd9, 0xa9, 0x39, 0x29, 0x89, 0x50, 0x17, 0x14, 0x64, 0xa7, 0xeb, 0x43, 0x5c, 0x04, 0xd2, 0x9b,
	0xc4, 0x06, 0x66, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xda, 0x21, 0xa5, 0x2d, 0xa7, 0x00,
	0x00, 0x00,
}
