// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blimp/cluster/v0/manager.proto

package cluster

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	errors "github.com/kelda/blimp/pkg/proto/errors"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CLIAction int32

const (
	CLIAction_OK   CLIAction = 0
	CLIAction_EXIT CLIAction = 1
)

var CLIAction_name = map[int32]string{
	0: "OK",
	1: "EXIT",
}

var CLIAction_value = map[string]int32{
	"OK":   0,
	"EXIT": 1,
}

func (x CLIAction) String() string {
	return proto.EnumName(CLIAction_name, int32(x))
}

func (CLIAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{0}
}

type ServicePhase int32

const (
	ServicePhase_UNKNOWN              ServicePhase = 0
	ServicePhase_INITIALIZING_VOLUMES ServicePhase = 1
	ServicePhase_WAIT_DEPENDS_ON      ServicePhase = 2
	ServicePhase_WAIT_SYNC_BIND       ServicePhase = 3
	ServicePhase_PENDING              ServicePhase = 4
	ServicePhase_RUNNING              ServicePhase = 5
	ServicePhase_EXITED               ServicePhase = 6
	ServicePhase_UNHEALTHY            ServicePhase = 7
	ServicePhase_UNSCHEDULABLE        ServicePhase = 8
)

var ServicePhase_name = map[int32]string{
	0: "UNKNOWN",
	1: "INITIALIZING_VOLUMES",
	2: "WAIT_DEPENDS_ON",
	3: "WAIT_SYNC_BIND",
	4: "PENDING",
	5: "RUNNING",
	6: "EXITED",
	7: "UNHEALTHY",
	8: "UNSCHEDULABLE",
}

var ServicePhase_value = map[string]int32{
	"UNKNOWN":              0,
	"INITIALIZING_VOLUMES": 1,
	"WAIT_DEPENDS_ON":      2,
	"WAIT_SYNC_BIND":       3,
	"PENDING":              4,
	"RUNNING":              5,
	"EXITED":               6,
	"UNHEALTHY":            7,
	"UNSCHEDULABLE":        8,
}

func (x ServicePhase) String() string {
	return proto.EnumName(ServicePhase_name, int32(x))
}

func (ServicePhase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{1}
}

type SandboxStatus_SandboxPhase int32

const (
	SandboxStatus_UNKNOWN        SandboxStatus_SandboxPhase = 0
	SandboxStatus_RUNNING        SandboxStatus_SandboxPhase = 1
	SandboxStatus_TERMINATING    SandboxStatus_SandboxPhase = 2
	SandboxStatus_DOES_NOT_EXIST SandboxStatus_SandboxPhase = 3
	SandboxStatus_PREPARING      SandboxStatus_SandboxPhase = 4
)

var SandboxStatus_SandboxPhase_name = map[int32]string{
	0: "UNKNOWN",
	1: "RUNNING",
	2: "TERMINATING",
	3: "DOES_NOT_EXIST",
	4: "PREPARING",
}

var SandboxStatus_SandboxPhase_value = map[string]int32{
	"UNKNOWN":        0,
	"RUNNING":        1,
	"TERMINATING":    2,
	"DOES_NOT_EXIST": 3,
	"PREPARING":      4,
}

func (x SandboxStatus_SandboxPhase) String() string {
	return proto.EnumName(SandboxStatus_SandboxPhase_name, int32(x))
}

func (SandboxStatus_SandboxPhase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{16, 0}
}

type ProxyAnalyticsRequest struct {
	// The JSON payload to post to DataDog on behalf of the client.
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyAnalyticsRequest) Reset()         { *m = ProxyAnalyticsRequest{} }
func (m *ProxyAnalyticsRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyAnalyticsRequest) ProtoMessage()    {}
func (*ProxyAnalyticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{0}
}

func (m *ProxyAnalyticsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyAnalyticsRequest.Unmarshal(m, b)
}
func (m *ProxyAnalyticsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyAnalyticsRequest.Marshal(b, m, deterministic)
}
func (m *ProxyAnalyticsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyAnalyticsRequest.Merge(m, src)
}
func (m *ProxyAnalyticsRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyAnalyticsRequest.Size(m)
}
func (m *ProxyAnalyticsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyAnalyticsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyAnalyticsRequest proto.InternalMessageInfo

func (m *ProxyAnalyticsRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ProxyAnalyticsResponse struct {
	Error                *errors.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProxyAnalyticsResponse) Reset()         { *m = ProxyAnalyticsResponse{} }
func (m *ProxyAnalyticsResponse) String() string { return proto.CompactTextString(m) }
func (*ProxyAnalyticsResponse) ProtoMessage()    {}
func (*ProxyAnalyticsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{1}
}

func (m *ProxyAnalyticsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyAnalyticsResponse.Unmarshal(m, b)
}
func (m *ProxyAnalyticsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyAnalyticsResponse.Marshal(b, m, deterministic)
}
func (m *ProxyAnalyticsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyAnalyticsResponse.Merge(m, src)
}
func (m *ProxyAnalyticsResponse) XXX_Size() int {
	return xxx_messageInfo_ProxyAnalyticsResponse.Size(m)
}
func (m *ProxyAnalyticsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyAnalyticsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyAnalyticsResponse proto.InternalMessageInfo

func (m *ProxyAnalyticsResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CheckVersionRequest struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVersionRequest) Reset()         { *m = CheckVersionRequest{} }
func (m *CheckVersionRequest) String() string { return proto.CompactTextString(m) }
func (*CheckVersionRequest) ProtoMessage()    {}
func (*CheckVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{2}
}

func (m *CheckVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVersionRequest.Unmarshal(m, b)
}
func (m *CheckVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVersionRequest.Marshal(b, m, deterministic)
}
func (m *CheckVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVersionRequest.Merge(m, src)
}
func (m *CheckVersionRequest) XXX_Size() int {
	return xxx_messageInfo_CheckVersionRequest.Size(m)
}
func (m *CheckVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVersionRequest proto.InternalMessageInfo

func (m *CheckVersionRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type CheckVersionResponse struct {
	Version              string        `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	DisplayMessage       string        `protobuf:"bytes,2,opt,name=display_message,json=displayMessage,proto3" json:"display_message,omitempty"`
	Action               CLIAction     `protobuf:"varint,3,opt,name=action,proto3,enum=blimp.cluster.v0.CLIAction" json:"action,omitempty"`
	Error                *errors.Error `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CheckVersionResponse) Reset()         { *m = CheckVersionResponse{} }
func (m *CheckVersionResponse) String() string { return proto.CompactTextString(m) }
func (*CheckVersionResponse) ProtoMessage()    {}
func (*CheckVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{3}
}

func (m *CheckVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVersionResponse.Unmarshal(m, b)
}
func (m *CheckVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVersionResponse.Marshal(b, m, deterministic)
}
func (m *CheckVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVersionResponse.Merge(m, src)
}
func (m *CheckVersionResponse) XXX_Size() int {
	return xxx_messageInfo_CheckVersionResponse.Size(m)
}
func (m *CheckVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVersionResponse proto.InternalMessageInfo

func (m *CheckVersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CheckVersionResponse) GetDisplayMessage() string {
	if m != nil {
		return m.DisplayMessage
	}
	return ""
}

func (m *CheckVersionResponse) GetAction() CLIAction {
	if m != nil {
		return m.Action
	}
	return CLIAction_OK
}

func (m *CheckVersionResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateSandboxRequest struct {
	Token                string                         `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ComposeFile          string                         `protobuf:"bytes,2,opt,name=composeFile,proto3" json:"composeFile,omitempty"`
	RegistryCredentials  map[string]*RegistryCredential `protobuf:"bytes,3,rep,name=registryCredentials,proto3" json:"registryCredentials,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SyncedFolders        map[string]string              `protobuf:"bytes,4,rep,name=syncedFolders,proto3" json:"syncedFolders,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *CreateSandboxRequest) Reset()         { *m = CreateSandboxRequest{} }
func (m *CreateSandboxRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSandboxRequest) ProtoMessage()    {}
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{4}
}

func (m *CreateSandboxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSandboxRequest.Unmarshal(m, b)
}
func (m *CreateSandboxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSandboxRequest.Marshal(b, m, deterministic)
}
func (m *CreateSandboxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSandboxRequest.Merge(m, src)
}
func (m *CreateSandboxRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSandboxRequest.Size(m)
}
func (m *CreateSandboxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSandboxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSandboxRequest proto.InternalMessageInfo

func (m *CreateSandboxRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateSandboxRequest) GetComposeFile() string {
	if m != nil {
		return m.ComposeFile
	}
	return ""
}

func (m *CreateSandboxRequest) GetRegistryCredentials() map[string]*RegistryCredential {
	if m != nil {
		return m.RegistryCredentials
	}
	return nil
}

func (m *CreateSandboxRequest) GetSyncedFolders() map[string]string {
	if m != nil {
		return m.SyncedFolders
	}
	return nil
}

type RegistryCredential struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistryCredential) Reset()         { *m = RegistryCredential{} }
func (m *RegistryCredential) String() string { return proto.CompactTextString(m) }
func (*RegistryCredential) ProtoMessage()    {}
func (*RegistryCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{5}
}

func (m *RegistryCredential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistryCredential.Unmarshal(m, b)
}
func (m *RegistryCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistryCredential.Marshal(b, m, deterministic)
}
func (m *RegistryCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistryCredential.Merge(m, src)
}
func (m *RegistryCredential) XXX_Size() int {
	return xxx_messageInfo_RegistryCredential.Size(m)
}
func (m *RegistryCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistryCredential.DiscardUnknown(m)
}

var xxx_messageInfo_RegistryCredential proto.InternalMessageInfo

func (m *RegistryCredential) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegistryCredential) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AttachToSandboxRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachToSandboxRequest) Reset()         { *m = AttachToSandboxRequest{} }
func (m *AttachToSandboxRequest) String() string { return proto.CompactTextString(m) }
func (*AttachToSandboxRequest) ProtoMessage()    {}
func (*AttachToSandboxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{6}
}

func (m *AttachToSandboxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachToSandboxRequest.Unmarshal(m, b)
}
func (m *AttachToSandboxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachToSandboxRequest.Marshal(b, m, deterministic)
}
func (m *AttachToSandboxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachToSandboxRequest.Merge(m, src)
}
func (m *AttachToSandboxRequest) XXX_Size() int {
	return xxx_messageInfo_AttachToSandboxRequest.Size(m)
}
func (m *AttachToSandboxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachToSandboxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachToSandboxRequest proto.InternalMessageInfo

func (m *AttachToSandboxRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AttachToSandboxResponse struct {
	Error                *errors.Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	NodeAddress          string           `protobuf:"bytes,2,opt,name=NodeAddress,proto3" json:"NodeAddress,omitempty"`
	NodeCert             string           `protobuf:"bytes,3,opt,name=NodeCert,proto3" json:"NodeCert,omitempty"`
	KubeCredentials      *KubeCredentials `protobuf:"bytes,4,opt,name=kubeCredentials,proto3" json:"kubeCredentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AttachToSandboxResponse) Reset()         { *m = AttachToSandboxResponse{} }
func (m *AttachToSandboxResponse) String() string { return proto.CompactTextString(m) }
func (*AttachToSandboxResponse) ProtoMessage()    {}
func (*AttachToSandboxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{7}
}

func (m *AttachToSandboxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachToSandboxResponse.Unmarshal(m, b)
}
func (m *AttachToSandboxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachToSandboxResponse.Marshal(b, m, deterministic)
}
func (m *AttachToSandboxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachToSandboxResponse.Merge(m, src)
}
func (m *AttachToSandboxResponse) XXX_Size() int {
	return xxx_messageInfo_AttachToSandboxResponse.Size(m)
}
func (m *AttachToSandboxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachToSandboxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttachToSandboxResponse proto.InternalMessageInfo

func (m *AttachToSandboxResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *AttachToSandboxResponse) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

func (m *AttachToSandboxResponse) GetNodeCert() string {
	if m != nil {
		return m.NodeCert
	}
	return ""
}

func (m *AttachToSandboxResponse) GetKubeCredentials() *KubeCredentials {
	if m != nil {
		return m.KubeCredentials
	}
	return nil
}

type CreateSandboxResponse struct {
	Error                *errors.Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	NodeAddress          string           `protobuf:"bytes,2,opt,name=NodeAddress,proto3" json:"NodeAddress,omitempty"`
	NodeCert             string           `protobuf:"bytes,3,opt,name=NodeCert,proto3" json:"NodeCert,omitempty"`
	KubeCredentials      *KubeCredentials `protobuf:"bytes,4,opt,name=kubeCredentials,proto3" json:"kubeCredentials,omitempty"`
	ImageNamespace       string           `protobuf:"bytes,5,opt,name=ImageNamespace,proto3" json:"ImageNamespace,omitempty"`
	Message              string           `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Action               CLIAction        `protobuf:"varint,7,opt,name=action,proto3,enum=blimp.cluster.v0.CLIAction" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateSandboxResponse) Reset()         { *m = CreateSandboxResponse{} }
func (m *CreateSandboxResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSandboxResponse) ProtoMessage()    {}
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{8}
}

func (m *CreateSandboxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSandboxResponse.Unmarshal(m, b)
}
func (m *CreateSandboxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSandboxResponse.Marshal(b, m, deterministic)
}
func (m *CreateSandboxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSandboxResponse.Merge(m, src)
}
func (m *CreateSandboxResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSandboxResponse.Size(m)
}
func (m *CreateSandboxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSandboxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSandboxResponse proto.InternalMessageInfo

func (m *CreateSandboxResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *CreateSandboxResponse) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

func (m *CreateSandboxResponse) GetNodeCert() string {
	if m != nil {
		return m.NodeCert
	}
	return ""
}

func (m *CreateSandboxResponse) GetKubeCredentials() *KubeCredentials {
	if m != nil {
		return m.KubeCredentials
	}
	return nil
}

func (m *CreateSandboxResponse) GetImageNamespace() string {
	if m != nil {
		return m.ImageNamespace
	}
	return ""
}

func (m *CreateSandboxResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateSandboxResponse) GetAction() CLIAction {
	if m != nil {
		return m.Action
	}
	return CLIAction_OK
}

type DeployRequest struct {
	Token                string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ComposeFile          string            `protobuf:"bytes,2,opt,name=composeFile,proto3" json:"composeFile,omitempty"`
	BuiltImages          map[string]string `protobuf:"bytes,3,rep,name=builtImages,proto3" json:"builtImages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeployRequest) Reset()         { *m = DeployRequest{} }
func (m *DeployRequest) String() string { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()    {}
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{9}
}

func (m *DeployRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployRequest.Unmarshal(m, b)
}
func (m *DeployRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployRequest.Marshal(b, m, deterministic)
}
func (m *DeployRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployRequest.Merge(m, src)
}
func (m *DeployRequest) XXX_Size() int {
	return xxx_messageInfo_DeployRequest.Size(m)
}
func (m *DeployRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployRequest proto.InternalMessageInfo

func (m *DeployRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeployRequest) GetComposeFile() string {
	if m != nil {
		return m.ComposeFile
	}
	return ""
}

func (m *DeployRequest) GetBuiltImages() map[string]string {
	if m != nil {
		return m.BuiltImages
	}
	return nil
}

type DeployResponse struct {
	Error                *errors.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeployResponse) Reset()         { *m = DeployResponse{} }
func (m *DeployResponse) String() string { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()    {}
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{10}
}

func (m *DeployResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResponse.Unmarshal(m, b)
}
func (m *DeployResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResponse.Marshal(b, m, deterministic)
}
func (m *DeployResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResponse.Merge(m, src)
}
func (m *DeployResponse) XXX_Size() int {
	return xxx_messageInfo_DeployResponse.Size(m)
}
func (m *DeployResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResponse proto.InternalMessageInfo

func (m *DeployResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type KubeCredentials struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	CaCrt                string   `protobuf:"bytes,2,opt,name=caCrt,proto3" json:"caCrt,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Namespace            string   `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubeCredentials) Reset()         { *m = KubeCredentials{} }
func (m *KubeCredentials) String() string { return proto.CompactTextString(m) }
func (*KubeCredentials) ProtoMessage()    {}
func (*KubeCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{11}
}

func (m *KubeCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubeCredentials.Unmarshal(m, b)
}
func (m *KubeCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubeCredentials.Marshal(b, m, deterministic)
}
func (m *KubeCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubeCredentials.Merge(m, src)
}
func (m *KubeCredentials) XXX_Size() int {
	return xxx_messageInfo_KubeCredentials.Size(m)
}
func (m *KubeCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_KubeCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_KubeCredentials proto.InternalMessageInfo

func (m *KubeCredentials) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *KubeCredentials) GetCaCrt() string {
	if m != nil {
		return m.CaCrt
	}
	return ""
}

func (m *KubeCredentials) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *KubeCredentials) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type DeleteSandboxRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DeleteVolumes        bool     `protobuf:"varint,2,opt,name=delete_volumes,json=deleteVolumes,proto3" json:"delete_volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSandboxRequest) Reset()         { *m = DeleteSandboxRequest{} }
func (m *DeleteSandboxRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSandboxRequest) ProtoMessage()    {}
func (*DeleteSandboxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{12}
}

func (m *DeleteSandboxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSandboxRequest.Unmarshal(m, b)
}
func (m *DeleteSandboxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSandboxRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSandboxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSandboxRequest.Merge(m, src)
}
func (m *DeleteSandboxRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSandboxRequest.Size(m)
}
func (m *DeleteSandboxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSandboxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSandboxRequest proto.InternalMessageInfo

func (m *DeleteSandboxRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteSandboxRequest) GetDeleteVolumes() bool {
	if m != nil {
		return m.DeleteVolumes
	}
	return false
}

type DeleteSandboxResponse struct {
	Error                *errors.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeleteSandboxResponse) Reset()         { *m = DeleteSandboxResponse{} }
func (m *DeleteSandboxResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSandboxResponse) ProtoMessage()    {}
func (*DeleteSandboxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{13}
}

func (m *DeleteSandboxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSandboxResponse.Unmarshal(m, b)
}
func (m *DeleteSandboxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSandboxResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSandboxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSandboxResponse.Merge(m, src)
}
func (m *DeleteSandboxResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSandboxResponse.Size(m)
}
func (m *DeleteSandboxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSandboxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSandboxResponse proto.InternalMessageInfo

func (m *DeleteSandboxResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetStatusRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{14}
}

func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

func (m *GetStatusRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetStatusResponse struct {
	Error                *errors.Error  `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Status               *SandboxStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{15}
}

func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetStatusResponse) GetStatus() *SandboxStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type SandboxStatus struct {
	Services             map[string]*ServiceStatus  `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Phase                SandboxStatus_SandboxPhase `protobuf:"varint,2,opt,name=phase,proto3,enum=blimp.cluster.v0.SandboxStatus_SandboxPhase" json:"phase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SandboxStatus) Reset()         { *m = SandboxStatus{} }
func (m *SandboxStatus) String() string { return proto.CompactTextString(m) }
func (*SandboxStatus) ProtoMessage()    {}
func (*SandboxStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{16}
}

func (m *SandboxStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SandboxStatus.Unmarshal(m, b)
}
func (m *SandboxStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SandboxStatus.Marshal(b, m, deterministic)
}
func (m *SandboxStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SandboxStatus.Merge(m, src)
}
func (m *SandboxStatus) XXX_Size() int {
	return xxx_messageInfo_SandboxStatus.Size(m)
}
func (m *SandboxStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SandboxStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SandboxStatus proto.InternalMessageInfo

func (m *SandboxStatus) GetServices() map[string]*ServiceStatus {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *SandboxStatus) GetPhase() SandboxStatus_SandboxPhase {
	if m != nil {
		return m.Phase
	}
	return SandboxStatus_UNKNOWN
}

type ServiceStatus struct {
	Phase                ServicePhase `protobuf:"varint,1,opt,name=phase,proto3,enum=blimp.cluster.v0.ServicePhase" json:"phase,omitempty"`
	Msg                  string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	HasStarted           bool         `protobuf:"varint,3,opt,name=has_started,json=hasStarted,proto3" json:"has_started,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ServiceStatus) Reset()         { *m = ServiceStatus{} }
func (m *ServiceStatus) String() string { return proto.CompactTextString(m) }
func (*ServiceStatus) ProtoMessage()    {}
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{17}
}

func (m *ServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatus.Unmarshal(m, b)
}
func (m *ServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatus.Marshal(b, m, deterministic)
}
func (m *ServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatus.Merge(m, src)
}
func (m *ServiceStatus) XXX_Size() int {
	return xxx_messageInfo_ServiceStatus.Size(m)
}
func (m *ServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatus proto.InternalMessageInfo

func (m *ServiceStatus) GetPhase() ServicePhase {
	if m != nil {
		return m.Phase
	}
	return ServicePhase_UNKNOWN
}

func (m *ServiceStatus) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ServiceStatus) GetHasStarted() bool {
	if m != nil {
		return m.HasStarted
	}
	return false
}

type RestartRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartRequest) Reset()         { *m = RestartRequest{} }
func (m *RestartRequest) String() string { return proto.CompactTextString(m) }
func (*RestartRequest) ProtoMessage()    {}
func (*RestartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{18}
}

func (m *RestartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartRequest.Unmarshal(m, b)
}
func (m *RestartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartRequest.Marshal(b, m, deterministic)
}
func (m *RestartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartRequest.Merge(m, src)
}
func (m *RestartRequest) XXX_Size() int {
	return xxx_messageInfo_RestartRequest.Size(m)
}
func (m *RestartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestartRequest proto.InternalMessageInfo

func (m *RestartRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RestartRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type RestartResponse struct {
	Error                *errors.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RestartResponse) Reset()         { *m = RestartResponse{} }
func (m *RestartResponse) String() string { return proto.CompactTextString(m) }
func (*RestartResponse) ProtoMessage()    {}
func (*RestartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{19}
}

func (m *RestartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartResponse.Unmarshal(m, b)
}
func (m *RestartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartResponse.Marshal(b, m, deterministic)
}
func (m *RestartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartResponse.Merge(m, src)
}
func (m *RestartResponse) XXX_Size() int {
	return xxx_messageInfo_RestartResponse.Size(m)
}
func (m *RestartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestartResponse proto.InternalMessageInfo

func (m *RestartResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type TagImageRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagImageRequest) Reset()         { *m = TagImageRequest{} }
func (m *TagImageRequest) String() string { return proto.CompactTextString(m) }
func (*TagImageRequest) ProtoMessage()    {}
func (*TagImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{20}
}

func (m *TagImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagImageRequest.Unmarshal(m, b)
}
func (m *TagImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagImageRequest.Marshal(b, m, deterministic)
}
func (m *TagImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagImageRequest.Merge(m, src)
}
func (m *TagImageRequest) XXX_Size() int {
	return xxx_messageInfo_TagImageRequest.Size(m)
}
func (m *TagImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TagImageRequest proto.InternalMessageInfo

func (m *TagImageRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *TagImageRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *TagImageRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type TagImagesRequest struct {
	Token                string                         `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TagRequests          []*TagImageRequest             `protobuf:"bytes,2,rep,name=tagRequests,proto3" json:"tagRequests,omitempty"`
	RegistryCredentials  map[string]*RegistryCredential `protobuf:"bytes,3,rep,name=registryCredentials,proto3" json:"registryCredentials,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *TagImagesRequest) Reset()         { *m = TagImagesRequest{} }
func (m *TagImagesRequest) String() string { return proto.CompactTextString(m) }
func (*TagImagesRequest) ProtoMessage()    {}
func (*TagImagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{21}
}

func (m *TagImagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagImagesRequest.Unmarshal(m, b)
}
func (m *TagImagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagImagesRequest.Marshal(b, m, deterministic)
}
func (m *TagImagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagImagesRequest.Merge(m, src)
}
func (m *TagImagesRequest) XXX_Size() int {
	return xxx_messageInfo_TagImagesRequest.Size(m)
}
func (m *TagImagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagImagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TagImagesRequest proto.InternalMessageInfo

func (m *TagImagesRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TagImagesRequest) GetTagRequests() []*TagImageRequest {
	if m != nil {
		return m.TagRequests
	}
	return nil
}

func (m *TagImagesRequest) GetRegistryCredentials() map[string]*RegistryCredential {
	if m != nil {
		return m.RegistryCredentials
	}
	return nil
}

type TagImagesResponse struct {
	Service              string        `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Error                *errors.Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TagImagesResponse) Reset()         { *m = TagImagesResponse{} }
func (m *TagImagesResponse) String() string { return proto.CompactTextString(m) }
func (*TagImagesResponse) ProtoMessage()    {}
func (*TagImagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{22}
}

func (m *TagImagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagImagesResponse.Unmarshal(m, b)
}
func (m *TagImagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagImagesResponse.Marshal(b, m, deterministic)
}
func (m *TagImagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagImagesResponse.Merge(m, src)
}
func (m *TagImagesResponse) XXX_Size() int {
	return xxx_messageInfo_TagImagesResponse.Size(m)
}
func (m *TagImagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TagImagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TagImagesResponse proto.InternalMessageInfo

func (m *TagImagesResponse) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *TagImagesResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ExposeRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExposeRequest) Reset()         { *m = ExposeRequest{} }
func (m *ExposeRequest) String() string { return proto.CompactTextString(m) }
func (*ExposeRequest) ProtoMessage()    {}
func (*ExposeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{23}
}

func (m *ExposeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExposeRequest.Unmarshal(m, b)
}
func (m *ExposeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExposeRequest.Marshal(b, m, deterministic)
}
func (m *ExposeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExposeRequest.Merge(m, src)
}
func (m *ExposeRequest) XXX_Size() int {
	return xxx_messageInfo_ExposeRequest.Size(m)
}
func (m *ExposeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExposeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExposeRequest proto.InternalMessageInfo

func (m *ExposeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ExposeRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ExposeRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type ExposeResponse struct {
	Error                *errors.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Link                 string        `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExposeResponse) Reset()         { *m = ExposeResponse{} }
func (m *ExposeResponse) String() string { return proto.CompactTextString(m) }
func (*ExposeResponse) ProtoMessage()    {}
func (*ExposeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{24}
}

func (m *ExposeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExposeResponse.Unmarshal(m, b)
}
func (m *ExposeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExposeResponse.Marshal(b, m, deterministic)
}
func (m *ExposeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExposeResponse.Merge(m, src)
}
func (m *ExposeResponse) XXX_Size() int {
	return xxx_messageInfo_ExposeResponse.Size(m)
}
func (m *ExposeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExposeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExposeResponse proto.InternalMessageInfo

func (m *ExposeResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ExposeResponse) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

type UnexposeRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnexposeRequest) Reset()         { *m = UnexposeRequest{} }
func (m *UnexposeRequest) String() string { return proto.CompactTextString(m) }
func (*UnexposeRequest) ProtoMessage()    {}
func (*UnexposeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{25}
}

func (m *UnexposeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnexposeRequest.Unmarshal(m, b)
}
func (m *UnexposeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnexposeRequest.Marshal(b, m, deterministic)
}
func (m *UnexposeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnexposeRequest.Merge(m, src)
}
func (m *UnexposeRequest) XXX_Size() int {
	return xxx_messageInfo_UnexposeRequest.Size(m)
}
func (m *UnexposeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnexposeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnexposeRequest proto.InternalMessageInfo

func (m *UnexposeRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UnexposeResponse struct {
	Error                *errors.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UnexposeResponse) Reset()         { *m = UnexposeResponse{} }
func (m *UnexposeResponse) String() string { return proto.CompactTextString(m) }
func (*UnexposeResponse) ProtoMessage()    {}
func (*UnexposeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{26}
}

func (m *UnexposeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnexposeResponse.Unmarshal(m, b)
}
func (m *UnexposeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnexposeResponse.Marshal(b, m, deterministic)
}
func (m *UnexposeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnexposeResponse.Merge(m, src)
}
func (m *UnexposeResponse) XXX_Size() int {
	return xxx_messageInfo_UnexposeResponse.Size(m)
}
func (m *UnexposeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnexposeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnexposeResponse proto.InternalMessageInfo

func (m *UnexposeResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterEnum("blimp.cluster.v0.CLIAction", CLIAction_name, CLIAction_value)
	proto.RegisterEnum("blimp.cluster.v0.ServicePhase", ServicePhase_name, ServicePhase_value)
	proto.RegisterEnum("blimp.cluster.v0.SandboxStatus_SandboxPhase", SandboxStatus_SandboxPhase_name, SandboxStatus_SandboxPhase_value)
	proto.RegisterType((*ProxyAnalyticsRequest)(nil), "blimp.cluster.v0.ProxyAnalyticsRequest")
	proto.RegisterType((*ProxyAnalyticsResponse)(nil), "blimp.cluster.v0.ProxyAnalyticsResponse")
	proto.RegisterType((*CheckVersionRequest)(nil), "blimp.cluster.v0.CheckVersionRequest")
	proto.RegisterType((*CheckVersionResponse)(nil), "blimp.cluster.v0.CheckVersionResponse")
	proto.RegisterType((*CreateSandboxRequest)(nil), "blimp.cluster.v0.CreateSandboxRequest")
	proto.RegisterMapType((map[string]*RegistryCredential)(nil), "blimp.cluster.v0.CreateSandboxRequest.RegistryCredentialsEntry")
	proto.RegisterMapType((map[string]string)(nil), "blimp.cluster.v0.CreateSandboxRequest.SyncedFoldersEntry")
	proto.RegisterType((*RegistryCredential)(nil), "blimp.cluster.v0.RegistryCredential")
	proto.RegisterType((*AttachToSandboxRequest)(nil), "blimp.cluster.v0.AttachToSandboxRequest")
	proto.RegisterType((*AttachToSandboxResponse)(nil), "blimp.cluster.v0.AttachToSandboxResponse")
	proto.RegisterType((*CreateSandboxResponse)(nil), "blimp.cluster.v0.CreateSandboxResponse")
	proto.RegisterType((*DeployRequest)(nil), "blimp.cluster.v0.DeployRequest")
	proto.RegisterMapType((map[string]string)(nil), "blimp.cluster.v0.DeployRequest.BuiltImagesEntry")
	proto.RegisterType((*DeployResponse)(nil), "blimp.cluster.v0.DeployResponse")
	proto.RegisterType((*KubeCredentials)(nil), "blimp.cluster.v0.KubeCredentials")
	proto.RegisterType((*DeleteSandboxRequest)(nil), "blimp.cluster.v0.DeleteSandboxRequest")
	proto.RegisterType((*DeleteSandboxResponse)(nil), "blimp.cluster.v0.DeleteSandboxResponse")
	proto.RegisterType((*GetStatusRequest)(nil), "blimp.cluster.v0.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "blimp.cluster.v0.GetStatusResponse")
	proto.RegisterType((*SandboxStatus)(nil), "blimp.cluster.v0.SandboxStatus")
	proto.RegisterMapType((map[string]*ServiceStatus)(nil), "blimp.cluster.v0.SandboxStatus.ServicesEntry")
	proto.RegisterType((*ServiceStatus)(nil), "blimp.cluster.v0.ServiceStatus")
	proto.RegisterType((*RestartRequest)(nil), "blimp.cluster.v0.RestartRequest")
	proto.RegisterType((*RestartResponse)(nil), "blimp.cluster.v0.RestartResponse")
	proto.RegisterType((*TagImageRequest)(nil), "blimp.cluster.v0.TagImageRequest")
	proto.RegisterType((*TagImagesRequest)(nil), "blimp.cluster.v0.TagImagesRequest")
	proto.RegisterMapType((map[string]*RegistryCredential)(nil), "blimp.cluster.v0.TagImagesRequest.RegistryCredentialsEntry")
	proto.RegisterType((*TagImagesResponse)(nil), "blimp.cluster.v0.TagImagesResponse")
	proto.RegisterType((*ExposeRequest)(nil), "blimp.cluster.v0.ExposeRequest")
	proto.RegisterType((*ExposeResponse)(nil), "blimp.cluster.v0.ExposeResponse")
	proto.RegisterType((*UnexposeRequest)(nil), "blimp.cluster.v0.UnexposeRequest")
	proto.RegisterType((*UnexposeResponse)(nil), "blimp.cluster.v0.UnexposeResponse")
}

func init() {
	proto.RegisterFile("blimp/cluster/v0/manager.proto", fileDescriptor_d156d5389f4d1cd6)
}

var fileDescriptor_d156d5389f4d1cd6 = []byte{
	// 1477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0x6f, 0x6f, 0xda, 0x46,
	0x18, 0x8f, 0x21, 0x21, 0xf0, 0x50, 0xc0, 0xbd, 0xa6, 0x1d, 0xf2, 0xba, 0x36, 0xf5, 0xd6, 0x36,
	0xeb, 0x3a, 0x12, 0xa5, 0x9b, 0xb6, 0x75, 0x52, 0x5b, 0x02, 0x6e, 0x6b, 0x25, 0x71, 0x22, 0x9b,
	0xa4, 0x7f, 0x56, 0x09, 0x19, 0x38, 0x01, 0xc2, 0x60, 0xea, 0x33, 0x2c, 0xec, 0x03, 0xed, 0x53,
	0xec, 0xfd, 0xa4, 0xbd, 0xec, 0xcb, 0xed, 0xc5, 0xbe, 0xca, 0x74, 0x3e, 0xdb, 0xd8, 0xd8, 0x01,
	0xc6, 0xa6, 0x49, 0x7b, 0x77, 0x77, 0xfe, 0x3d, 0x7f, 0xef, 0xb9, 0xdf, 0x3d, 0x3e, 0xb8, 0xd5,
	0x30, 0xba, 0xfd, 0xe1, 0x6e, 0xd3, 0x18, 0x11, 0x1b, 0x5b, 0xbb, 0xe3, 0xbd, 0xdd, 0xbe, 0x3e,
	0xd0, 0xdb, 0xd8, 0x2a, 0x0d, 0x2d, 0xd3, 0x36, 0x11, 0xef, 0x7c, 0x2f, 0xb9, 0xdf, 0x4b, 0xe3,
	0x3d, 0xe1, 0x26, 0x93, 0xc0, 0x96, 0x65, 0x5a, 0x84, 0x0a, 0xb0, 0x11, 0xc3, 0x8b, 0x5f, 0xc0,
	0xf5, 0x53, 0xcb, 0xbc, 0x98, 0x94, 0x07, 0xba, 0x31, 0xb1, 0xbb, 0x4d, 0xa2, 0xe2, 0xf7, 0x23,
	0x4c, 0x6c, 0x84, 0x60, 0xbd, 0x61, 0xb6, 0x26, 0x45, 0x6e, 0x9b, 0xdb, 0xc9, 0xa8, 0xce, 0x58,
	0x7c, 0x0e, 0x37, 0x66, 0xc1, 0x64, 0x68, 0x0e, 0x08, 0x46, 0x0f, 0x61, 0xc3, 0x51, 0xeb, 0xc0,
	0xb3, 0xfb, 0x37, 0x4a, 0xcc, 0x0d, 0xd7, 0xd4, 0x78, 0xaf, 0x24, 0xd1, 0x91, 0xca, 0x40, 0xe2,
	0x2e, 0x5c, 0xab, 0x74, 0x70, 0xb3, 0x77, 0x8e, 0x2d, 0xd2, 0x35, 0x07, 0x9e, 0xc9, 0x22, 0x6c,
	0x8e, 0xd9, 0x8a, 0x6b, 0xd5, 0x9b, 0x8a, 0xbf, 0x70, 0xb0, 0x15, 0x96, 0x70, 0xed, 0x5e, 0x2a,
	0x82, 0xee, 0x43, 0xa1, 0xd5, 0x25, 0x43, 0x43, 0x9f, 0xd4, 0xfb, 0x98, 0x10, 0xbd, 0x8d, 0x8b,
	0x09, 0x07, 0x91, 0x77, 0x97, 0x8f, 0xd9, 0x2a, 0x7a, 0x04, 0x29, 0xbd, 0x69, 0x53, 0x0d, 0xc9,
	0x6d, 0x6e, 0x27, 0xbf, 0xff, 0x71, 0x69, 0x36, 0x85, 0xa5, 0xca, 0x91, 0x5c, 0x76, 0x20, 0xaa,
	0x0b, 0x9d, 0xc6, 0xbb, 0xbe, 0x4c, 0xbc, 0x1f, 0x92, 0xb0, 0x55, 0xb1, 0xb0, 0x6e, 0x63, 0x4d,
	0x1f, 0xb4, 0x1a, 0xe6, 0x85, 0x17, 0xf1, 0x16, 0x6c, 0xd8, 0x66, 0x0f, 0x7b, 0xce, 0xb3, 0x09,
	0xda, 0x86, 0x6c, 0xd3, 0xec, 0x0f, 0x4d, 0x82, 0x9f, 0x77, 0x0d, 0xcf, 0xed, 0xe0, 0x12, 0x7a,
	0x0f, 0xd7, 0x2c, 0xdc, 0xee, 0x12, 0xdb, 0x9a, 0x54, 0x2c, 0xdc, 0xc2, 0x03, 0xbb, 0xab, 0x1b,
	0xa4, 0x98, 0xdc, 0x4e, 0xee, 0x64, 0xf7, 0x9f, 0xc6, 0x04, 0x10, 0x63, 0xbc, 0xa4, 0x46, 0x35,
	0x48, 0x03, 0xdb, 0x9a, 0xa8, 0x71, 0xba, 0x51, 0x1d, 0x72, 0x64, 0x32, 0x68, 0xe2, 0xd6, 0x73,
	0xd3, 0x68, 0x61, 0x8b, 0x14, 0xd7, 0x1d, 0x63, 0xdf, 0x2d, 0x69, 0x4c, 0x0b, 0xca, 0x32, 0x33,
	0x61, 0x7d, 0x82, 0x01, 0xc5, 0xcb, 0x3c, 0x42, 0x3c, 0x24, 0x7b, 0xd8, 0xab, 0x45, 0x3a, 0x44,
	0x8f, 0x61, 0x63, 0xac, 0x1b, 0x23, 0x96, 0x9d, 0xec, 0xfe, 0x67, 0x51, 0x37, 0xa2, 0xca, 0x54,
	0x26, 0xf2, 0x38, 0xf1, 0x2d, 0x27, 0x3c, 0x03, 0x14, 0x75, 0x29, 0xc6, 0xce, 0x56, 0xd0, 0x4e,
	0x26, 0xa0, 0x41, 0x3c, 0x02, 0x14, 0x35, 0x81, 0x04, 0x48, 0x8f, 0x08, 0xb6, 0x06, 0x7a, 0x1f,
	0xbb, 0x6a, 0xfc, 0x39, 0xfd, 0x36, 0xd4, 0x09, 0xf9, 0xd1, 0xb4, 0x5a, 0xae, 0x3a, 0x7f, 0x2e,
	0x96, 0xe0, 0x46, 0xd9, 0xb6, 0xf5, 0x66, 0xa7, 0x66, 0x2e, 0x53, 0x23, 0xe2, 0x07, 0x0e, 0x3e,
	0x8a, 0x08, 0xac, 0x72, 0x18, 0x69, 0xb5, 0x29, 0x66, 0x0b, 0x97, 0x5b, 0x2d, 0x0b, 0x13, 0xe2,
	0x55, 0x5b, 0x60, 0x89, 0xfa, 0x4d, 0xa7, 0x15, 0x6c, 0xd9, 0xce, 0x19, 0xc9, 0xa8, 0xfe, 0x1c,
	0x1d, 0x42, 0xa1, 0x37, 0x6a, 0xe0, 0x60, 0x15, 0xb2, 0x23, 0x71, 0x27, 0xba, 0x23, 0x87, 0x61,
	0xa0, 0x3a, 0x2b, 0x29, 0xfe, 0x9a, 0x80, 0xeb, 0x33, 0xd5, 0xf3, 0x3f, 0x0f, 0x09, 0xdd, 0x83,
	0xbc, 0xdc, 0xd7, 0xdb, 0x58, 0xd1, 0xfb, 0x98, 0x0c, 0xf5, 0x26, 0x2e, 0x6e, 0x30, 0x16, 0x0a,
	0xaf, 0x52, 0x22, 0xf3, 0x68, 0x2a, 0xc5, 0x88, 0xac, 0x1f, 0xe1, 0xa7, 0xcd, 0xa5, 0xf9, 0x49,
	0xfc, 0x83, 0x83, 0x5c, 0x15, 0x0f, 0x0d, 0x73, 0xf2, 0x4f, 0xa9, 0x46, 0x85, 0x6c, 0x63, 0xd4,
	0x35, 0x6c, 0xc7, 0x5f, 0x8f, 0x62, 0xf6, 0xa2, 0x3e, 0x84, 0xac, 0x95, 0x0e, 0xa6, 0x22, 0xec,
	0xb0, 0x07, 0x95, 0x08, 0x4f, 0x80, 0x9f, 0x05, 0xfc, 0xad, 0xa3, 0xf7, 0x04, 0xf2, 0x9e, 0xb9,
	0x95, 0xee, 0x1f, 0x13, 0x0a, 0x33, 0x1b, 0x47, 0xaf, 0xbb, 0x8e, 0x49, 0x6c, 0xef, 0xba, 0xa3,
	0x63, 0xea, 0x40, 0x53, 0xaf, 0x58, 0xb6, 0xe7, 0x80, 0x33, 0x99, 0x26, 0x32, 0x19, 0x4c, 0xe4,
	0x4d, 0xc8, 0x0c, 0xfc, 0x2d, 0x5e, 0x77, 0xbe, 0x4c, 0x17, 0x44, 0x0d, 0xb6, 0xaa, 0xd8, 0xc0,
	0x4b, 0xf2, 0xff, 0x5d, 0xc8, 0xb7, 0x1c, 0x74, 0x7d, 0x6c, 0x1a, 0xa3, 0x3e, 0x66, 0x15, 0x9c,
	0x56, 0x73, 0x6c, 0xf5, 0x9c, 0x2d, 0x8a, 0x12, 0x5c, 0x9f, 0x51, 0xba, 0x52, 0x32, 0x76, 0x80,
	0x7f, 0x81, 0x6d, 0xcd, 0xd6, 0xed, 0x11, 0x99, 0xcf, 0x39, 0x3f, 0xc1, 0xd5, 0x00, 0x72, 0xa5,
	0x93, 0xf9, 0x0d, 0xa4, 0x88, 0x23, 0xef, 0xf2, 0xf6, 0xed, 0x68, 0x21, 0xb9, 0xd1, 0xb8, 0x66,
	0x5c, 0xb8, 0xf8, 0x7b, 0x02, 0x72, 0xa1, 0x2f, 0x48, 0x86, 0x34, 0xc1, 0xd6, 0xb8, 0xdb, 0xc4,
	0xa4, 0xc8, 0x39, 0x55, 0xf9, 0xe5, 0x02, 0x65, 0x25, 0xcd, 0xc5, 0xb3, 0x92, 0xf4, 0xc5, 0xd1,
	0x01, 0x6c, 0x0c, 0x3b, 0x3a, 0x61, 0x95, 0x96, 0xdf, 0x7f, 0xb8, 0x50, 0x0f, 0x9b, 0x9d, 0x52,
	0x19, 0x95, 0x89, 0x0a, 0xef, 0x20, 0x17, 0x52, 0x1f, 0x53, 0xd0, 0x5f, 0x87, 0xef, 0xac, 0xb8,
	0xd8, 0x99, 0x06, 0x37, 0xf6, 0x40, 0xc5, 0xbf, 0x83, 0x2b, 0x41, 0xa3, 0x28, 0x0b, 0x9b, 0x67,
	0xca, 0xa1, 0x72, 0xf2, 0x4a, 0xe1, 0xd7, 0xe8, 0x44, 0x3d, 0x53, 0x14, 0x59, 0x79, 0xc1, 0x73,
	0xa8, 0x00, 0xd9, 0x9a, 0xa4, 0x1e, 0xcb, 0x4a, 0xb9, 0x46, 0x17, 0x12, 0x08, 0x41, 0xbe, 0x7a,
	0x22, 0x69, 0x75, 0xe5, 0xa4, 0x56, 0x97, 0x5e, 0xcb, 0x5a, 0x8d, 0x4f, 0xa2, 0x1c, 0x64, 0x4e,
	0x55, 0xe9, 0xb4, 0xac, 0x52, 0xc8, 0xba, 0x78, 0xe1, 0xfb, 0xee, 0xe6, 0xf6, 0x2b, 0x2f, 0x21,
	0x9c, 0x93, 0x90, 0x5b, 0x97, 0x7a, 0x1a, 0x4c, 0x01, 0x8d, 0xb8, 0x4f, 0xda, 0xee, 0x69, 0xa1,
	0x43, 0x74, 0x1b, 0xb2, 0x1d, 0x9d, 0xd4, 0x89, 0xad, 0x5b, 0x36, 0x6e, 0x39, 0x27, 0x26, 0xad,
	0x42, 0x47, 0x27, 0x1a, 0x5b, 0x11, 0x9f, 0x41, 0x5e, 0xc5, 0xce, 0xe7, 0xf9, 0x47, 0xa2, 0x08,
	0x9b, 0xee, 0x6e, 0xb9, 0xea, 0xbd, 0xa9, 0xf8, 0x14, 0x0a, 0xbe, 0x86, 0x95, 0xea, 0x5f, 0x83,
	0x42, 0x4d, 0x6f, 0x3b, 0x54, 0x14, 0x68, 0x44, 0x3d, 0x6b, 0x5c, 0xc8, 0x1a, 0xf5, 0xae, 0xdb,
	0x9f, 0xf6, 0x92, 0x6c, 0x42, 0x03, 0xb7, 0xf5, 0xb6, 0x4b, 0x08, 0x74, 0x28, 0xfe, 0x96, 0x00,
	0xde, 0xd3, 0x3a, 0xff, 0x54, 0xa1, 0x0a, 0x64, 0x6d, 0xbd, 0xed, 0x62, 0xe8, 0xb9, 0x48, 0xc6,
	0x5f, 0x35, 0x33, 0x4e, 0xaa, 0x41, 0x29, 0xd4, 0x9f, 0xd7, 0x10, 0x7e, 0x7f, 0xb9, 0x32, 0xb2,
	0x52, 0x33, 0xf8, 0xdf, 0xf6, 0x6a, 0xe2, 0x0f, 0x70, 0x35, 0xe0, 0xef, 0xb4, 0xf3, 0xbf, 0x64,
	0x8f, 0xfc, 0xed, 0x4f, 0x2c, 0xb7, 0xfd, 0x39, 0xe9, 0x82, 0xde, 0x76, 0x2b, 0x16, 0x20, 0xbd,
	0x39, 0x86, 0xa6, 0xdb, 0x46, 0xe4, 0x54, 0x67, 0x2c, 0xaa, 0x90, 0xf7, 0x94, 0xae, 0x44, 0x93,
	0x08, 0xd6, 0x8d, 0xee, 0xa0, 0xe7, 0x9a, 0x72, 0xc6, 0xe2, 0x7d, 0x28, 0x9c, 0x0d, 0xf0, 0x62,
	0x57, 0xc5, 0x67, 0xc0, 0x4f, 0x81, 0xab, 0x98, 0x7f, 0xf0, 0x09, 0x64, 0xfc, 0x96, 0x02, 0xa5,
	0x20, 0x71, 0x72, 0xc8, 0xaf, 0xa1, 0x34, 0xac, 0x4b, 0xaf, 0xe5, 0x1a, 0xcf, 0x3d, 0xf8, 0x99,
	0x83, 0x2b, 0xc1, 0xf3, 0x1f, 0x66, 0xa3, 0x22, 0x6c, 0xc9, 0x8a, 0x5c, 0x93, 0xcb, 0x47, 0xf2,
	0x5b, 0x59, 0x79, 0x51, 0x3f, 0x3f, 0x39, 0x3a, 0x3b, 0x96, 0x34, 0x9e, 0x43, 0xd7, 0xa0, 0xf0,
	0xaa, 0x2c, 0xd7, 0xea, 0x55, 0xe9, 0x54, 0x52, 0xaa, 0x5a, 0xfd, 0x44, 0x61, 0xf4, 0xe4, 0x2c,
	0x6a, 0x6f, 0x94, 0x4a, 0xfd, 0x40, 0x56, 0xaa, 0x7c, 0x92, 0xea, 0xa3, 0x08, 0x87, 0x9c, 0x82,
	0xec, 0xb6, 0x81, 0x00, 0x52, 0xd4, 0x09, 0xa9, 0xca, 0xa7, 0x28, 0x89, 0x9d, 0x29, 0x2f, 0xa5,
	0xf2, 0x51, 0xed, 0xe5, 0x1b, 0x7e, 0x13, 0x5d, 0x85, 0xdc, 0x99, 0xa2, 0x55, 0x5e, 0x4a, 0xd5,
	0xb3, 0xa3, 0xf2, 0xc1, 0x91, 0xc4, 0xa7, 0xf7, 0xff, 0x4c, 0xc3, 0xe6, 0x31, 0xfb, 0x3d, 0x46,
	0x1d, 0x28, 0xcc, 0xf4, 0xcb, 0x68, 0x27, 0x5a, 0x88, 0xf1, 0x3d, 0xb8, 0xf0, 0xf9, 0x12, 0x48,
	0x96, 0x69, 0x71, 0x0d, 0x35, 0x20, 0x17, 0x6a, 0x62, 0xd1, 0xbd, 0xe5, 0xfe, 0x91, 0x84, 0xfb,
	0x0b, 0x71, 0xbe, 0x8d, 0x73, 0x28, 0xb0, 0x0e, 0x68, 0x1a, 0xcd, 0xed, 0x05, 0x3d, 0x99, 0xb0,
	0x7d, 0x39, 0x20, 0xe8, 0x7b, 0xa8, 0xa7, 0x88, 0xf3, 0x3d, 0xae, 0x93, 0x89, 0xf3, 0x3d, 0xb6,
	0x39, 0x71, 0x7c, 0xcf, 0xf8, 0x6d, 0x04, 0x12, 0xa3, 0x72, 0xb3, 0xdd, 0x88, 0xf0, 0xe9, 0x5c,
	0x8c, 0xaf, 0x17, 0x43, 0x3e, 0xfc, 0x3a, 0x81, 0x62, 0x9c, 0x8a, 0x7d, 0xec, 0x10, 0x76, 0x16,
	0x03, 0x7d, 0x33, 0x6f, 0x21, 0xfb, 0x4a, 0xb7, 0x9b, 0x9d, 0x7f, 0x3d, 0x80, 0x3d, 0x0e, 0xd5,
	0xe1, 0x4a, 0xf0, 0x99, 0x03, 0xdd, 0x8d, 0xa9, 0x88, 0xe8, 0xc3, 0x89, 0x70, 0x6f, 0x11, 0xcc,
	0x77, 0xfe, 0x14, 0x36, 0xdd, 0xdb, 0x12, 0x6d, 0xc7, 0xd1, 0x70, 0xf0, 0x2a, 0x16, 0xee, 0xcc,
	0x41, 0xf8, 0x1a, 0x5f, 0x43, 0xc6, 0x27, 0xe7, 0xb8, 0x64, 0xcc, 0xde, 0x34, 0x71, 0xc9, 0x88,
	0xb0, 0xbb, 0x93, 0x8c, 0x63, 0x48, 0x31, 0x12, 0x8d, 0x2b, 0xed, 0x10, 0x67, 0xc7, 0x95, 0x76,
	0x98, 0x7f, 0xc5, 0x35, 0xa4, 0x41, 0xda, 0xa3, 0x45, 0x14, 0x13, 0xd9, 0x0c, 0xb7, 0x0a, 0xe2,
	0x3c, 0x88, 0xa7, 0xf4, 0xe0, 0xc1, 0xdb, 0x9d, 0x76, 0xd7, 0xee, 0x8c, 0x1a, 0xa5, 0xa6, 0xd9,
	0xdf, 0xed, 0x61, 0xa3, 0xa5, 0xef, 0xb2, 0xf7, 0xb6, 0x61, 0xaf, 0xbd, 0xeb, 0x3c, 0xb1, 0x79,
	0x6f, 0x75, 0x8d, 0x94, 0x33, 0x7d, 0xf4, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xea, 0x5f,
	0x17, 0xc3, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerClient interface {
	AttachToSandbox(ctx context.Context, in *AttachToSandboxRequest, opts ...grpc.CallOption) (*AttachToSandboxResponse, error)
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	DeployToSandbox(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
	DeleteSandbox(ctx context.Context, in *DeleteSandboxRequest, opts ...grpc.CallOption) (*DeleteSandboxResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	ProxyAnalytics(ctx context.Context, in *ProxyAnalyticsRequest, opts ...grpc.CallOption) (*ProxyAnalyticsResponse, error)
	WatchStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (Manager_WatchStatusClient, error)
	CheckVersion(ctx context.Context, in *CheckVersionRequest, opts ...grpc.CallOption) (*CheckVersionResponse, error)
	Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error)
	TagImages(ctx context.Context, in *TagImagesRequest, opts ...grpc.CallOption) (Manager_TagImagesClient, error)
	Expose(ctx context.Context, in *ExposeRequest, opts ...grpc.CallOption) (*ExposeResponse, error)
	Unexpose(ctx context.Context, in *UnexposeRequest, opts ...grpc.CallOption) (*UnexposeResponse, error)
}

type managerClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerClient(cc grpc.ClientConnInterface) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) AttachToSandbox(ctx context.Context, in *AttachToSandboxRequest, opts ...grpc.CallOption) (*AttachToSandboxResponse, error) {
	out := new(AttachToSandboxResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/AttachToSandbox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/CreateSandbox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) DeployToSandbox(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/DeployToSandbox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) DeleteSandbox(ctx context.Context, in *DeleteSandboxRequest, opts ...grpc.CallOption) (*DeleteSandboxResponse, error) {
	out := new(DeleteSandboxResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/DeleteSandbox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) ProxyAnalytics(ctx context.Context, in *ProxyAnalyticsRequest, opts ...grpc.CallOption) (*ProxyAnalyticsResponse, error) {
	out := new(ProxyAnalyticsResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/ProxyAnalytics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) WatchStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (Manager_WatchStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Manager_serviceDesc.Streams[0], "/blimp.cluster.v0.Manager/WatchStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &managerWatchStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Manager_WatchStatusClient interface {
	Recv() (*GetStatusResponse, error)
	grpc.ClientStream
}

type managerWatchStatusClient struct {
	grpc.ClientStream
}

func (x *managerWatchStatusClient) Recv() (*GetStatusResponse, error) {
	m := new(GetStatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *managerClient) CheckVersion(ctx context.Context, in *CheckVersionRequest, opts ...grpc.CallOption) (*CheckVersionResponse, error) {
	out := new(CheckVersionResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/CheckVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error) {
	out := new(RestartResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/Restart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) TagImages(ctx context.Context, in *TagImagesRequest, opts ...grpc.CallOption) (Manager_TagImagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Manager_serviceDesc.Streams[1], "/blimp.cluster.v0.Manager/TagImages", opts...)
	if err != nil {
		return nil, err
	}
	x := &managerTagImagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Manager_TagImagesClient interface {
	Recv() (*TagImagesResponse, error)
	grpc.ClientStream
}

type managerTagImagesClient struct {
	grpc.ClientStream
}

func (x *managerTagImagesClient) Recv() (*TagImagesResponse, error) {
	m := new(TagImagesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *managerClient) Expose(ctx context.Context, in *ExposeRequest, opts ...grpc.CallOption) (*ExposeResponse, error) {
	out := new(ExposeResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/Expose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Unexpose(ctx context.Context, in *UnexposeRequest, opts ...grpc.CallOption) (*UnexposeResponse, error) {
	out := new(UnexposeResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/Unexpose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServer is the server API for Manager service.
type ManagerServer interface {
	AttachToSandbox(context.Context, *AttachToSandboxRequest) (*AttachToSandboxResponse, error)
	CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	DeployToSandbox(context.Context, *DeployRequest) (*DeployResponse, error)
	DeleteSandbox(context.Context, *DeleteSandboxRequest) (*DeleteSandboxResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	ProxyAnalytics(context.Context, *ProxyAnalyticsRequest) (*ProxyAnalyticsResponse, error)
	WatchStatus(*GetStatusRequest, Manager_WatchStatusServer) error
	CheckVersion(context.Context, *CheckVersionRequest) (*CheckVersionResponse, error)
	Restart(context.Context, *RestartRequest) (*RestartResponse, error)
	TagImages(*TagImagesRequest, Manager_TagImagesServer) error
	Expose(context.Context, *ExposeRequest) (*ExposeResponse, error)
	Unexpose(context.Context, *UnexposeRequest) (*UnexposeResponse, error)
}

// UnimplementedManagerServer can be embedded to have forward compatible implementations.
type UnimplementedManagerServer struct {
}

func (*UnimplementedManagerServer) AttachToSandbox(ctx context.Context, req *AttachToSandboxRequest) (*AttachToSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachToSandbox not implemented")
}
func (*UnimplementedManagerServer) CreateSandbox(ctx context.Context, req *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (*UnimplementedManagerServer) DeployToSandbox(ctx context.Context, req *DeployRequest) (*DeployResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployToSandbox not implemented")
}
func (*UnimplementedManagerServer) DeleteSandbox(ctx context.Context, req *DeleteSandboxRequest) (*DeleteSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSandbox not implemented")
}
func (*UnimplementedManagerServer) GetStatus(ctx context.Context, req *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (*UnimplementedManagerServer) ProxyAnalytics(ctx context.Context, req *ProxyAnalyticsRequest) (*ProxyAnalyticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyAnalytics not implemented")
}
func (*UnimplementedManagerServer) WatchStatus(req *GetStatusRequest, srv Manager_WatchStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchStatus not implemented")
}
func (*UnimplementedManagerServer) CheckVersion(ctx context.Context, req *CheckVersionRequest) (*CheckVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckVersion not implemented")
}
func (*UnimplementedManagerServer) Restart(ctx context.Context, req *RestartRequest) (*RestartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restart not implemented")
}
func (*UnimplementedManagerServer) TagImages(req *TagImagesRequest, srv Manager_TagImagesServer) error {
	return status.Errorf(codes.Unimplemented, "method TagImages not implemented")
}
func (*UnimplementedManagerServer) Expose(ctx context.Context, req *ExposeRequest) (*ExposeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Expose not implemented")
}
func (*UnimplementedManagerServer) Unexpose(ctx context.Context, req *UnexposeRequest) (*UnexposeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unexpose not implemented")
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_AttachToSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachToSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).AttachToSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/AttachToSandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).AttachToSandbox(ctx, req.(*AttachToSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/CreateSandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_DeployToSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).DeployToSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/DeployToSandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).DeployToSandbox(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_DeleteSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).DeleteSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/DeleteSandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).DeleteSandbox(ctx, req.(*DeleteSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_ProxyAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).ProxyAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/ProxyAnalytics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).ProxyAnalytics(ctx, req.(*ProxyAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_WatchStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerServer).WatchStatus(m, &managerWatchStatusServer{stream})
}

type Manager_WatchStatusServer interface {
	Send(*GetStatusResponse) error
	grpc.ServerStream
}

type managerWatchStatusServer struct {
	grpc.ServerStream
}

func (x *managerWatchStatusServer) Send(m *GetStatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Manager_CheckVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).CheckVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/CheckVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).CheckVersion(ctx, req.(*CheckVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/Restart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Restart(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_TagImages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TagImagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerServer).TagImages(m, &managerTagImagesServer{stream})
}

type Manager_TagImagesServer interface {
	Send(*TagImagesResponse) error
	grpc.ServerStream
}

type managerTagImagesServer struct {
	grpc.ServerStream
}

func (x *managerTagImagesServer) Send(m *TagImagesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Manager_Expose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Expose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/Expose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Expose(ctx, req.(*ExposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Unexpose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnexposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Unexpose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/Unexpose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Unexpose(ctx, req.(*UnexposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blimp.cluster.v0.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AttachToSandbox",
			Handler:    _Manager_AttachToSandbox_Handler,
		},
		{
			MethodName: "CreateSandbox",
			Handler:    _Manager_CreateSandbox_Handler,
		},
		{
			MethodName: "DeployToSandbox",
			Handler:    _Manager_DeployToSandbox_Handler,
		},
		{
			MethodName: "DeleteSandbox",
			Handler:    _Manager_DeleteSandbox_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Manager_GetStatus_Handler,
		},
		{
			MethodName: "ProxyAnalytics",
			Handler:    _Manager_ProxyAnalytics_Handler,
		},
		{
			MethodName: "CheckVersion",
			Handler:    _Manager_CheckVersion_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _Manager_Restart_Handler,
		},
		{
			MethodName: "Expose",
			Handler:    _Manager_Expose_Handler,
		},
		{
			MethodName: "Unexpose",
			Handler:    _Manager_Unexpose_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStatus",
			Handler:       _Manager_WatchStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TagImages",
			Handler:       _Manager_TagImages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blimp/cluster/v0/manager.proto",
}
