// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blimp/cluster/v0/manager.proto

package cluster

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckVersionResponse_Action int32

const (
	CheckVersionResponse_OK   CheckVersionResponse_Action = 0
	CheckVersionResponse_EXIT CheckVersionResponse_Action = 1
)

var CheckVersionResponse_Action_name = map[int32]string{
	0: "OK",
	1: "EXIT",
}

var CheckVersionResponse_Action_value = map[string]int32{
	"OK":   0,
	"EXIT": 1,
}

func (x CheckVersionResponse_Action) String() string {
	return proto.EnumName(CheckVersionResponse_Action_name, int32(x))
}

func (CheckVersionResponse_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{1, 0}
}

type CheckVersionRequest struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVersionRequest) Reset()         { *m = CheckVersionRequest{} }
func (m *CheckVersionRequest) String() string { return proto.CompactTextString(m) }
func (*CheckVersionRequest) ProtoMessage()    {}
func (*CheckVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{0}
}

func (m *CheckVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVersionRequest.Unmarshal(m, b)
}
func (m *CheckVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVersionRequest.Marshal(b, m, deterministic)
}
func (m *CheckVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVersionRequest.Merge(m, src)
}
func (m *CheckVersionRequest) XXX_Size() int {
	return xxx_messageInfo_CheckVersionRequest.Size(m)
}
func (m *CheckVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVersionRequest proto.InternalMessageInfo

func (m *CheckVersionRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type CheckVersionResponse struct {
	Version              string                      `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	DisplayMessage       string                      `protobuf:"bytes,2,opt,name=DisplayMessage,proto3" json:"DisplayMessage,omitempty"`
	Action               CheckVersionResponse_Action `protobuf:"varint,3,opt,name=action,proto3,enum=blimp.cluster.v0.CheckVersionResponse_Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CheckVersionResponse) Reset()         { *m = CheckVersionResponse{} }
func (m *CheckVersionResponse) String() string { return proto.CompactTextString(m) }
func (*CheckVersionResponse) ProtoMessage()    {}
func (*CheckVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{1}
}

func (m *CheckVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVersionResponse.Unmarshal(m, b)
}
func (m *CheckVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVersionResponse.Marshal(b, m, deterministic)
}
func (m *CheckVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVersionResponse.Merge(m, src)
}
func (m *CheckVersionResponse) XXX_Size() int {
	return xxx_messageInfo_CheckVersionResponse.Size(m)
}
func (m *CheckVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVersionResponse proto.InternalMessageInfo

func (m *CheckVersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CheckVersionResponse) GetDisplayMessage() string {
	if m != nil {
		return m.DisplayMessage
	}
	return ""
}

func (m *CheckVersionResponse) GetAction() CheckVersionResponse_Action {
	if m != nil {
		return m.Action
	}
	return CheckVersionResponse_OK
}

type CreateSandboxRequest struct {
	Token                string                         `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ComposeFile          *ComposeFile                   `protobuf:"bytes,2,opt,name=composeFile,proto3" json:"composeFile,omitempty"`
	RegistryCredentials  map[string]*RegistryCredential `protobuf:"bytes,3,rep,name=registryCredentials,proto3" json:"registryCredentials,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *CreateSandboxRequest) Reset()         { *m = CreateSandboxRequest{} }
func (m *CreateSandboxRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSandboxRequest) ProtoMessage()    {}
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{2}
}

func (m *CreateSandboxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSandboxRequest.Unmarshal(m, b)
}
func (m *CreateSandboxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSandboxRequest.Marshal(b, m, deterministic)
}
func (m *CreateSandboxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSandboxRequest.Merge(m, src)
}
func (m *CreateSandboxRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSandboxRequest.Size(m)
}
func (m *CreateSandboxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSandboxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSandboxRequest proto.InternalMessageInfo

func (m *CreateSandboxRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateSandboxRequest) GetComposeFile() *ComposeFile {
	if m != nil {
		return m.ComposeFile
	}
	return nil
}

func (m *CreateSandboxRequest) GetRegistryCredentials() map[string]*RegistryCredential {
	if m != nil {
		return m.RegistryCredentials
	}
	return nil
}

type RegistryCredential struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistryCredential) Reset()         { *m = RegistryCredential{} }
func (m *RegistryCredential) String() string { return proto.CompactTextString(m) }
func (*RegistryCredential) ProtoMessage()    {}
func (*RegistryCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{3}
}

func (m *RegistryCredential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistryCredential.Unmarshal(m, b)
}
func (m *RegistryCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistryCredential.Marshal(b, m, deterministic)
}
func (m *RegistryCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistryCredential.Merge(m, src)
}
func (m *RegistryCredential) XXX_Size() int {
	return xxx_messageInfo_RegistryCredential.Size(m)
}
func (m *RegistryCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistryCredential.DiscardUnknown(m)
}

var xxx_messageInfo_RegistryCredential proto.InternalMessageInfo

func (m *RegistryCredential) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegistryCredential) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateSandboxResponse struct {
	SandboxAddress       string           `protobuf:"bytes,1,opt,name=SandboxAddress,proto3" json:"SandboxAddress,omitempty"`
	SandboxCert          string           `protobuf:"bytes,2,opt,name=SandboxCert,proto3" json:"SandboxCert,omitempty"`
	KubeCredentials      *KubeCredentials `protobuf:"bytes,3,opt,name=kubeCredentials,proto3" json:"kubeCredentials,omitempty"`
	ImageNamespace       string           `protobuf:"bytes,4,opt,name=ImageNamespace,proto3" json:"ImageNamespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateSandboxResponse) Reset()         { *m = CreateSandboxResponse{} }
func (m *CreateSandboxResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSandboxResponse) ProtoMessage()    {}
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{4}
}

func (m *CreateSandboxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSandboxResponse.Unmarshal(m, b)
}
func (m *CreateSandboxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSandboxResponse.Marshal(b, m, deterministic)
}
func (m *CreateSandboxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSandboxResponse.Merge(m, src)
}
func (m *CreateSandboxResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSandboxResponse.Size(m)
}
func (m *CreateSandboxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSandboxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSandboxResponse proto.InternalMessageInfo

func (m *CreateSandboxResponse) GetSandboxAddress() string {
	if m != nil {
		return m.SandboxAddress
	}
	return ""
}

func (m *CreateSandboxResponse) GetSandboxCert() string {
	if m != nil {
		return m.SandboxCert
	}
	return ""
}

func (m *CreateSandboxResponse) GetKubeCredentials() *KubeCredentials {
	if m != nil {
		return m.KubeCredentials
	}
	return nil
}

func (m *CreateSandboxResponse) GetImageNamespace() string {
	if m != nil {
		return m.ImageNamespace
	}
	return ""
}

type DeployRequest struct {
	Token                string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ComposeFile          *ComposeFile      `protobuf:"bytes,2,opt,name=composeFile,proto3" json:"composeFile,omitempty"`
	BuiltImages          map[string]string `protobuf:"bytes,3,rep,name=builtImages,proto3" json:"builtImages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeployRequest) Reset()         { *m = DeployRequest{} }
func (m *DeployRequest) String() string { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()    {}
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{5}
}

func (m *DeployRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployRequest.Unmarshal(m, b)
}
func (m *DeployRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployRequest.Marshal(b, m, deterministic)
}
func (m *DeployRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployRequest.Merge(m, src)
}
func (m *DeployRequest) XXX_Size() int {
	return xxx_messageInfo_DeployRequest.Size(m)
}
func (m *DeployRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployRequest proto.InternalMessageInfo

func (m *DeployRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeployRequest) GetComposeFile() *ComposeFile {
	if m != nil {
		return m.ComposeFile
	}
	return nil
}

func (m *DeployRequest) GetBuiltImages() map[string]string {
	if m != nil {
		return m.BuiltImages
	}
	return nil
}

type ComposeFile struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Contents             string   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComposeFile) Reset()         { *m = ComposeFile{} }
func (m *ComposeFile) String() string { return proto.CompactTextString(m) }
func (*ComposeFile) ProtoMessage()    {}
func (*ComposeFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{6}
}

func (m *ComposeFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComposeFile.Unmarshal(m, b)
}
func (m *ComposeFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComposeFile.Marshal(b, m, deterministic)
}
func (m *ComposeFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComposeFile.Merge(m, src)
}
func (m *ComposeFile) XXX_Size() int {
	return xxx_messageInfo_ComposeFile.Size(m)
}
func (m *ComposeFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ComposeFile.DiscardUnknown(m)
}

var xxx_messageInfo_ComposeFile proto.InternalMessageInfo

func (m *ComposeFile) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ComposeFile) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

type DeployResponse struct {
	StrictParseError     string   `protobuf:"bytes,1,opt,name=strict_parse_error,json=strictParseError,proto3" json:"strict_parse_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployResponse) Reset()         { *m = DeployResponse{} }
func (m *DeployResponse) String() string { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()    {}
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{7}
}

func (m *DeployResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResponse.Unmarshal(m, b)
}
func (m *DeployResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResponse.Marshal(b, m, deterministic)
}
func (m *DeployResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResponse.Merge(m, src)
}
func (m *DeployResponse) XXX_Size() int {
	return xxx_messageInfo_DeployResponse.Size(m)
}
func (m *DeployResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResponse proto.InternalMessageInfo

func (m *DeployResponse) GetStrictParseError() string {
	if m != nil {
		return m.StrictParseError
	}
	return ""
}

type KubeCredentials struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	CaCrt                string   `protobuf:"bytes,2,opt,name=caCrt,proto3" json:"caCrt,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Namespace            string   `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubeCredentials) Reset()         { *m = KubeCredentials{} }
func (m *KubeCredentials) String() string { return proto.CompactTextString(m) }
func (*KubeCredentials) ProtoMessage()    {}
func (*KubeCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{8}
}

func (m *KubeCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubeCredentials.Unmarshal(m, b)
}
func (m *KubeCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubeCredentials.Marshal(b, m, deterministic)
}
func (m *KubeCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubeCredentials.Merge(m, src)
}
func (m *KubeCredentials) XXX_Size() int {
	return xxx_messageInfo_KubeCredentials.Size(m)
}
func (m *KubeCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_KubeCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_KubeCredentials proto.InternalMessageInfo

func (m *KubeCredentials) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *KubeCredentials) GetCaCrt() string {
	if m != nil {
		return m.CaCrt
	}
	return ""
}

func (m *KubeCredentials) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *KubeCredentials) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type DeleteSandboxRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSandboxRequest) Reset()         { *m = DeleteSandboxRequest{} }
func (m *DeleteSandboxRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSandboxRequest) ProtoMessage()    {}
func (*DeleteSandboxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{9}
}

func (m *DeleteSandboxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSandboxRequest.Unmarshal(m, b)
}
func (m *DeleteSandboxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSandboxRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSandboxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSandboxRequest.Merge(m, src)
}
func (m *DeleteSandboxRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSandboxRequest.Size(m)
}
func (m *DeleteSandboxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSandboxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSandboxRequest proto.InternalMessageInfo

func (m *DeleteSandboxRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeleteSandboxResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSandboxResponse) Reset()         { *m = DeleteSandboxResponse{} }
func (m *DeleteSandboxResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSandboxResponse) ProtoMessage()    {}
func (*DeleteSandboxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{10}
}

func (m *DeleteSandboxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSandboxResponse.Unmarshal(m, b)
}
func (m *DeleteSandboxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSandboxResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSandboxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSandboxResponse.Merge(m, src)
}
func (m *DeleteSandboxResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSandboxResponse.Size(m)
}
func (m *DeleteSandboxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSandboxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSandboxResponse proto.InternalMessageInfo

type GetStatusRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{11}
}

func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

func (m *GetStatusRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetStatusResponse struct {
	Status               *SandboxStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{12}
}

func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetStatus() *SandboxStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type SandboxStatus struct {
	Services             map[string]*ServiceStatus `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SandboxStatus) Reset()         { *m = SandboxStatus{} }
func (m *SandboxStatus) String() string { return proto.CompactTextString(m) }
func (*SandboxStatus) ProtoMessage()    {}
func (*SandboxStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{13}
}

func (m *SandboxStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SandboxStatus.Unmarshal(m, b)
}
func (m *SandboxStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SandboxStatus.Marshal(b, m, deterministic)
}
func (m *SandboxStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SandboxStatus.Merge(m, src)
}
func (m *SandboxStatus) XXX_Size() int {
	return xxx_messageInfo_SandboxStatus.Size(m)
}
func (m *SandboxStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SandboxStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SandboxStatus proto.InternalMessageInfo

func (m *SandboxStatus) GetServices() map[string]*ServiceStatus {
	if m != nil {
		return m.Services
	}
	return nil
}

type ServiceStatus struct {
	Phase                string   `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceStatus) Reset()         { *m = ServiceStatus{} }
func (m *ServiceStatus) String() string { return proto.CompactTextString(m) }
func (*ServiceStatus) ProtoMessage()    {}
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d156d5389f4d1cd6, []int{14}
}

func (m *ServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatus.Unmarshal(m, b)
}
func (m *ServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatus.Marshal(b, m, deterministic)
}
func (m *ServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatus.Merge(m, src)
}
func (m *ServiceStatus) XXX_Size() int {
	return xxx_messageInfo_ServiceStatus.Size(m)
}
func (m *ServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatus proto.InternalMessageInfo

func (m *ServiceStatus) GetPhase() string {
	if m != nil {
		return m.Phase
	}
	return ""
}

func init() {
	proto.RegisterEnum("blimp.cluster.v0.CheckVersionResponse_Action", CheckVersionResponse_Action_name, CheckVersionResponse_Action_value)
	proto.RegisterType((*CheckVersionRequest)(nil), "blimp.cluster.v0.CheckVersionRequest")
	proto.RegisterType((*CheckVersionResponse)(nil), "blimp.cluster.v0.CheckVersionResponse")
	proto.RegisterType((*CreateSandboxRequest)(nil), "blimp.cluster.v0.CreateSandboxRequest")
	proto.RegisterMapType((map[string]*RegistryCredential)(nil), "blimp.cluster.v0.CreateSandboxRequest.RegistryCredentialsEntry")
	proto.RegisterType((*RegistryCredential)(nil), "blimp.cluster.v0.RegistryCredential")
	proto.RegisterType((*CreateSandboxResponse)(nil), "blimp.cluster.v0.CreateSandboxResponse")
	proto.RegisterType((*DeployRequest)(nil), "blimp.cluster.v0.DeployRequest")
	proto.RegisterMapType((map[string]string)(nil), "blimp.cluster.v0.DeployRequest.BuiltImagesEntry")
	proto.RegisterType((*ComposeFile)(nil), "blimp.cluster.v0.ComposeFile")
	proto.RegisterType((*DeployResponse)(nil), "blimp.cluster.v0.DeployResponse")
	proto.RegisterType((*KubeCredentials)(nil), "blimp.cluster.v0.KubeCredentials")
	proto.RegisterType((*DeleteSandboxRequest)(nil), "blimp.cluster.v0.DeleteSandboxRequest")
	proto.RegisterType((*DeleteSandboxResponse)(nil), "blimp.cluster.v0.DeleteSandboxResponse")
	proto.RegisterType((*GetStatusRequest)(nil), "blimp.cluster.v0.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "blimp.cluster.v0.GetStatusResponse")
	proto.RegisterType((*SandboxStatus)(nil), "blimp.cluster.v0.SandboxStatus")
	proto.RegisterMapType((map[string]*ServiceStatus)(nil), "blimp.cluster.v0.SandboxStatus.ServicesEntry")
	proto.RegisterType((*ServiceStatus)(nil), "blimp.cluster.v0.ServiceStatus")
}

func init() {
	proto.RegisterFile("blimp/cluster/v0/manager.proto", fileDescriptor_d156d5389f4d1cd6)
}

var fileDescriptor_d156d5389f4d1cd6 = []byte{
	// 852 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5d, 0x6f, 0x1b, 0x45,
	0x14, 0xcd, 0xc6, 0x89, 0x9b, 0x5c, 0x93, 0xc4, 0x4c, 0x5d, 0x61, 0x59, 0x40, 0xcd, 0x42, 0x43,
	0x1e, 0x92, 0x75, 0x64, 0x84, 0x40, 0x95, 0x68, 0xd5, 0x3a, 0x01, 0x45, 0x69, 0x01, 0x6d, 0xaa,
	0x80, 0x2a, 0xa4, 0x68, 0xbc, 0xbe, 0xb2, 0x57, 0x5e, 0xef, 0x6c, 0x67, 0x66, 0x0d, 0xfe, 0x67,
	0x48, 0x48, 0xfc, 0x04, 0x1e, 0xf9, 0x31, 0x3c, 0xa1, 0xd9, 0x99, 0xdd, 0xec, 0x57, 0xeb, 0x3c,
	0xc0, 0xdb, 0xde, 0x7b, 0xcf, 0x39, 0x73, 0xc6, 0x73, 0x32, 0x19, 0xf8, 0x78, 0x1c, 0xf8, 0x8b,
	0x68, 0xe0, 0x05, 0xb1, 0x90, 0xc8, 0x07, 0xcb, 0xd3, 0xc1, 0x82, 0x86, 0x74, 0x8a, 0xdc, 0x89,
	0x38, 0x93, 0x8c, 0xb4, 0x93, 0xb9, 0x63, 0xe6, 0xce, 0xf2, 0xd4, 0x1e, 0xc0, 0xfd, 0xd1, 0x0c,
	0xbd, 0xf9, 0x35, 0x72, 0xe1, 0xb3, 0xd0, 0xc5, 0x37, 0x31, 0x0a, 0x49, 0xba, 0x70, 0x6f, 0xa9,
	0x3b, 0x5d, 0xab, 0x6f, 0x1d, 0xed, 0xba, 0x69, 0x69, 0xff, 0x61, 0x41, 0xa7, 0xc8, 0x10, 0x11,
	0x0b, 0x05, 0x2a, 0xca, 0x75, 0x91, 0x62, 0x4a, 0x72, 0x08, 0xfb, 0x67, 0xbe, 0x88, 0x02, 0xba,
	0x7a, 0x89, 0x42, 0xd0, 0x29, 0x76, 0x37, 0x13, 0x40, 0xa9, 0x4b, 0xce, 0xa1, 0x49, 0x3d, 0xa9,
	0x04, 0x1a, 0x7d, 0xeb, 0x68, 0x7f, 0x78, 0xe2, 0x94, 0xed, 0x3a, 0x75, 0x2b, 0x3b, 0xcf, 0x12,
	0x92, 0x6b, 0xc8, 0x76, 0x0f, 0x9a, 0xba, 0x43, 0x9a, 0xb0, 0xf9, 0xc3, 0x65, 0x7b, 0x83, 0xec,
	0xc0, 0xd6, 0xf9, 0xcf, 0x17, 0xaf, 0xda, 0x96, 0xfd, 0xd7, 0x26, 0x74, 0x46, 0x1c, 0xa9, 0xc4,
	0x2b, 0x1a, 0x4e, 0xc6, 0xec, 0xb7, 0x74, 0xc3, 0x1d, 0xd8, 0x96, 0x6c, 0x8e, 0xa9, 0x77, 0x5d,
	0x90, 0xa7, 0xd0, 0xf2, 0xd8, 0x22, 0x62, 0x02, 0xbf, 0xf5, 0x03, 0x6d, 0xbb, 0x35, 0xfc, 0xa8,
	0xc6, 0xd6, 0x2d, 0xc8, 0xcd, 0x33, 0xc8, 0x1b, 0xb8, 0xcf, 0x71, 0xea, 0x0b, 0xc9, 0x57, 0x23,
	0x8e, 0x13, 0x0c, 0xa5, 0x4f, 0x03, 0xd1, 0x6d, 0xf4, 0x1b, 0x47, 0xad, 0xe1, 0xd3, 0x1a, 0xa1,
	0x1a, 0x6f, 0x8e, 0x5b, 0x55, 0x38, 0x0f, 0x25, 0x5f, 0xb9, 0x75, 0xda, 0xbd, 0x00, 0xba, 0x6f,
	0x23, 0x90, 0x36, 0x34, 0xe6, 0xb8, 0x32, 0x7b, 0x54, 0x9f, 0xe4, 0x31, 0x6c, 0x2f, 0x69, 0x10,
	0xa7, 0x7b, 0xfb, 0xac, 0x6a, 0xa9, 0x2a, 0xe6, 0x6a, 0xca, 0xe3, 0xcd, 0xaf, 0x2d, 0xfb, 0x05,
	0x90, 0x2a, 0x80, 0xf4, 0x60, 0x27, 0x16, 0xc8, 0x43, 0xba, 0x40, 0xb3, 0x58, 0x56, 0xab, 0x59,
	0x44, 0x85, 0xf8, 0x95, 0xf1, 0x89, 0xc9, 0x41, 0x56, 0xdb, 0x7f, 0x5b, 0xf0, 0xa0, 0xf4, 0x13,
	0x98, 0x74, 0x1d, 0xc2, 0xbe, 0x69, 0x3d, 0x9b, 0x4c, 0x38, 0x0a, 0x61, 0x74, 0x4b, 0x5d, 0xd2,
	0x87, 0x96, 0xe9, 0x8c, 0x90, 0x4b, 0xb3, 0x40, 0xbe, 0x45, 0x2e, 0xe1, 0x60, 0x1e, 0x8f, 0xb1,
	0x78, 0x1c, 0x6a, 0xef, 0x9f, 0x54, 0xf7, 0x7e, 0x59, 0x04, 0xba, 0x65, 0xa6, 0xb2, 0x75, 0xb1,
	0xa0, 0x53, 0xfc, 0x9e, 0x2e, 0x50, 0x44, 0xd4, 0xc3, 0xee, 0x96, 0xb6, 0x55, 0xec, 0xda, 0xff,
	0x58, 0xb0, 0x77, 0x86, 0x51, 0xc0, 0x56, 0xff, 0x73, 0xe0, 0x5c, 0x68, 0x8d, 0x63, 0x3f, 0x90,
	0xc9, 0xfa, 0x69, 0xd0, 0x4e, 0xab, 0x02, 0x05, 0x33, 0xce, 0xf3, 0x5b, 0x8a, 0x4e, 0x56, 0x5e,
	0xa4, 0xf7, 0x04, 0xda, 0x65, 0x40, 0x4d, 0x92, 0x3a, 0xf9, 0x24, 0xed, 0xe6, 0x33, 0xf2, 0x0d,
	0xb4, 0x72, 0x7e, 0x09, 0x81, 0xad, 0x88, 0xca, 0x99, 0xe1, 0x26, 0xdf, 0x2a, 0x14, 0x1e, 0x0b,
	0x25, 0x86, 0x52, 0xa4, 0xa1, 0x48, 0x6b, 0xfb, 0x09, 0xec, 0xa7, 0x6e, 0x4d, 0x18, 0x8e, 0x81,
	0x08, 0xc9, 0x7d, 0x4f, 0xde, 0x44, 0x94, 0x0b, 0xbc, 0x41, 0xce, 0x19, 0x37, 0x7a, 0x6d, 0x3d,
	0xf9, 0x51, 0x0d, 0xce, 0x55, 0xdf, 0x66, 0x70, 0x50, 0x3a, 0x47, 0x65, 0x61, 0xc6, 0x84, 0x4c,
	0x2d, 0xa8, 0x6f, 0xe5, 0xdf, 0xa3, 0xa3, 0x2c, 0x33, 0xba, 0xb8, 0x3d, 0xa6, 0x46, 0xfe, 0x98,
	0x3e, 0x84, 0xdd, 0xb0, 0x74, 0xe2, 0xb7, 0x0d, 0xfb, 0x18, 0x3a, 0x67, 0x18, 0xe0, 0xdd, 0xee,
	0x18, 0xfb, 0x03, 0x78, 0x50, 0x42, 0xeb, 0x5d, 0xda, 0x47, 0xd0, 0xfe, 0x0e, 0xe5, 0x95, 0xa4,
	0x32, 0x16, 0xef, 0x96, 0x78, 0x01, 0xef, 0xe7, 0x90, 0xe6, 0x47, 0xfa, 0x0a, 0x9a, 0x22, 0xe9,
	0x24, 0xd8, 0xd6, 0xf0, 0x61, 0x35, 0x04, 0x66, 0x45, 0x43, 0x34, 0x70, 0xfb, 0x77, 0x0b, 0xf6,
	0x0a, 0x13, 0x72, 0x01, 0x3b, 0x02, 0xf9, 0xd2, 0xf7, 0x50, 0x89, 0xa9, 0x44, 0x9d, 0xac, 0x11,
	0x73, 0xae, 0x0c, 0x5e, 0xc7, 0x29, 0xa3, 0xf7, 0x7e, 0x81, 0xbd, 0xc2, 0xa8, 0x26, 0x48, 0x5f,
	0x16, 0xaf, 0xa4, 0x3a, 0xdf, 0x5a, 0xc1, 0xf8, 0xce, 0x25, 0xed, 0x51, 0xa6, 0x6e, 0x9c, 0x77,
	0x60, 0x3b, 0x9a, 0x51, 0x91, 0xde, 0x42, 0xba, 0x18, 0xfe, 0xb9, 0x05, 0xf7, 0x5e, 0xea, 0x7f,
	0x8c, 0x64, 0x0c, 0x7b, 0x85, 0x1b, 0x87, 0x1c, 0xde, 0xed, 0x56, 0xee, 0x7d, 0xbe, 0x16, 0x67,
	0xce, 0x71, 0x83, 0x5c, 0xc3, 0x81, 0x4e, 0xf0, 0x2b, 0x96, 0xae, 0xf2, 0x70, 0xcd, 0x9f, 0x64,
	0xaf, 0xff, 0x76, 0x40, 0xa6, 0x3b, 0x56, 0x97, 0x4a, 0x2e, 0x3a, 0x75, 0xde, 0xeb, 0x92, 0x58,
	0xe7, 0xbd, 0x3e, 0x83, 0xca, 0xfb, 0x6e, 0x96, 0x2d, 0x62, 0x57, 0x79, 0xe5, 0x88, 0xf6, 0x3e,
	0x7d, 0x27, 0x26, 0xd3, 0x7d, 0x0d, 0xad, 0x9f, 0xa8, 0xf4, 0x66, 0xff, 0xb9, 0xf2, 0xa9, 0x45,
	0x6e, 0xe0, 0xbd, 0xfc, 0x43, 0x81, 0x3c, 0x5a, 0xf7, 0x90, 0xd0, 0xfa, 0x87, 0x77, 0x7b, 0x6f,
	0xd8, 0x1b, 0xcf, 0x9d, 0xd7, 0xc7, 0x53, 0x5f, 0xce, 0xe2, 0xb1, 0xe3, 0xb1, 0xc5, 0x60, 0x8e,
	0xc1, 0x84, 0x9e, 0xf8, 0xa1, 0x37, 0xd0, 0xcf, 0xaf, 0x68, 0x3e, 0x1d, 0x24, 0xef, 0xad, 0xf4,
	0x21, 0x36, 0x6e, 0x26, 0xe5, 0x17, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x2d, 0x11, 0x27,
	0xa0, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerClient interface {
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	DeployToSandbox(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
	DeleteSandbox(ctx context.Context, in *DeleteSandboxRequest, opts ...grpc.CallOption) (*DeleteSandboxResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	WatchStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (Manager_WatchStatusClient, error)
	CheckVersion(ctx context.Context, in *CheckVersionRequest, opts ...grpc.CallOption) (*CheckVersionResponse, error)
}

type managerClient struct {
	cc grpc.ClientConnInterface
}

func NewManagerClient(cc grpc.ClientConnInterface) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/CreateSandbox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) DeployToSandbox(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/DeployToSandbox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) DeleteSandbox(ctx context.Context, in *DeleteSandboxRequest, opts ...grpc.CallOption) (*DeleteSandboxResponse, error) {
	out := new(DeleteSandboxResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/DeleteSandbox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) WatchStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (Manager_WatchStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Manager_serviceDesc.Streams[0], "/blimp.cluster.v0.Manager/WatchStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &managerWatchStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Manager_WatchStatusClient interface {
	Recv() (*GetStatusResponse, error)
	grpc.ClientStream
}

type managerWatchStatusClient struct {
	grpc.ClientStream
}

func (x *managerWatchStatusClient) Recv() (*GetStatusResponse, error) {
	m := new(GetStatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *managerClient) CheckVersion(ctx context.Context, in *CheckVersionRequest, opts ...grpc.CallOption) (*CheckVersionResponse, error) {
	out := new(CheckVersionResponse)
	err := c.cc.Invoke(ctx, "/blimp.cluster.v0.Manager/CheckVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagerServer is the server API for Manager service.
type ManagerServer interface {
	CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	DeployToSandbox(context.Context, *DeployRequest) (*DeployResponse, error)
	DeleteSandbox(context.Context, *DeleteSandboxRequest) (*DeleteSandboxResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	WatchStatus(*GetStatusRequest, Manager_WatchStatusServer) error
	CheckVersion(context.Context, *CheckVersionRequest) (*CheckVersionResponse, error)
}

// UnimplementedManagerServer can be embedded to have forward compatible implementations.
type UnimplementedManagerServer struct {
}

func (*UnimplementedManagerServer) CreateSandbox(ctx context.Context, req *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (*UnimplementedManagerServer) DeployToSandbox(ctx context.Context, req *DeployRequest) (*DeployResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployToSandbox not implemented")
}
func (*UnimplementedManagerServer) DeleteSandbox(ctx context.Context, req *DeleteSandboxRequest) (*DeleteSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSandbox not implemented")
}
func (*UnimplementedManagerServer) GetStatus(ctx context.Context, req *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (*UnimplementedManagerServer) WatchStatus(req *GetStatusRequest, srv Manager_WatchStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchStatus not implemented")
}
func (*UnimplementedManagerServer) CheckVersion(ctx context.Context, req *CheckVersionRequest) (*CheckVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckVersion not implemented")
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/CreateSandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_DeployToSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).DeployToSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/DeployToSandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).DeployToSandbox(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_DeleteSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).DeleteSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/DeleteSandbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).DeleteSandbox(ctx, req.(*DeleteSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_WatchStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerServer).WatchStatus(m, &managerWatchStatusServer{stream})
}

type Manager_WatchStatusServer interface {
	Send(*GetStatusResponse) error
	grpc.ServerStream
}

type managerWatchStatusServer struct {
	grpc.ServerStream
}

func (x *managerWatchStatusServer) Send(m *GetStatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Manager_CheckVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).CheckVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.cluster.v0.Manager/CheckVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).CheckVersion(ctx, req.(*CheckVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blimp.cluster.v0.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _Manager_CreateSandbox_Handler,
		},
		{
			MethodName: "DeployToSandbox",
			Handler:    _Manager_DeployToSandbox_Handler,
		},
		{
			MethodName: "DeleteSandbox",
			Handler:    _Manager_DeleteSandbox_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Manager_GetStatus_Handler,
		},
		{
			MethodName: "CheckVersion",
			Handler:    _Manager_CheckVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStatus",
			Handler:       _Manager_WatchStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blimp/cluster/v0/manager.proto",
}
