// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blimp/sandbox/v0/waiter.proto

package sandbox

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckReadyRequest struct {
	WaitSpec             *WaitSpec `protobuf:"bytes,1,opt,name=wait_spec,json=waitSpec,proto3" json:"wait_spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CheckReadyRequest) Reset()         { *m = CheckReadyRequest{} }
func (m *CheckReadyRequest) String() string { return proto.CompactTextString(m) }
func (*CheckReadyRequest) ProtoMessage()    {}
func (*CheckReadyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_845dc80cbf17fb57, []int{0}
}

func (m *CheckReadyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckReadyRequest.Unmarshal(m, b)
}
func (m *CheckReadyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckReadyRequest.Marshal(b, m, deterministic)
}
func (m *CheckReadyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckReadyRequest.Merge(m, src)
}
func (m *CheckReadyRequest) XXX_Size() int {
	return xxx_messageInfo_CheckReadyRequest.Size(m)
}
func (m *CheckReadyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckReadyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckReadyRequest proto.InternalMessageInfo

func (m *CheckReadyRequest) GetWaitSpec() *WaitSpec {
	if m != nil {
		return m.WaitSpec
	}
	return nil
}

type WaitSpec struct {
	DependsOn            []string `protobuf:"bytes,1,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	BindVolumes          []string `protobuf:"bytes,2,rep,name=bind_volumes,json=bindVolumes,proto3" json:"bind_volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitSpec) Reset()         { *m = WaitSpec{} }
func (m *WaitSpec) String() string { return proto.CompactTextString(m) }
func (*WaitSpec) ProtoMessage()    {}
func (*WaitSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_845dc80cbf17fb57, []int{1}
}

func (m *WaitSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitSpec.Unmarshal(m, b)
}
func (m *WaitSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitSpec.Marshal(b, m, deterministic)
}
func (m *WaitSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitSpec.Merge(m, src)
}
func (m *WaitSpec) XXX_Size() int {
	return xxx_messageInfo_WaitSpec.Size(m)
}
func (m *WaitSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitSpec.DiscardUnknown(m)
}

var xxx_messageInfo_WaitSpec proto.InternalMessageInfo

func (m *WaitSpec) GetDependsOn() []string {
	if m != nil {
		return m.DependsOn
	}
	return nil
}

func (m *WaitSpec) GetBindVolumes() []string {
	if m != nil {
		return m.BindVolumes
	}
	return nil
}

type CheckReadyResponse struct {
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// An optional message providing more information on why the container
	// needs to wait.
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckReadyResponse) Reset()         { *m = CheckReadyResponse{} }
func (m *CheckReadyResponse) String() string { return proto.CompactTextString(m) }
func (*CheckReadyResponse) ProtoMessage()    {}
func (*CheckReadyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_845dc80cbf17fb57, []int{2}
}

func (m *CheckReadyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckReadyResponse.Unmarshal(m, b)
}
func (m *CheckReadyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckReadyResponse.Marshal(b, m, deterministic)
}
func (m *CheckReadyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckReadyResponse.Merge(m, src)
}
func (m *CheckReadyResponse) XXX_Size() int {
	return xxx_messageInfo_CheckReadyResponse.Size(m)
}
func (m *CheckReadyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckReadyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckReadyResponse proto.InternalMessageInfo

func (m *CheckReadyResponse) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

func (m *CheckReadyResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckReadyRequest)(nil), "blimp.sandbox.v0.CheckReadyRequest")
	proto.RegisterType((*WaitSpec)(nil), "blimp.sandbox.v0.WaitSpec")
	proto.RegisterType((*CheckReadyResponse)(nil), "blimp.sandbox.v0.CheckReadyResponse")
}

func init() {
	proto.RegisterFile("blimp/sandbox/v0/waiter.proto", fileDescriptor_845dc80cbf17fb57)
}

var fileDescriptor_845dc80cbf17fb57 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4b, 0x33, 0x31,
	0x10, 0xc5, 0xbf, 0xed, 0x87, 0xa5, 0x3b, 0xf5, 0xa0, 0x41, 0x64, 0x29, 0x14, 0xea, 0xea, 0xa1,
	0x07, 0x4d, 0x4a, 0x3d, 0x78, 0xaf, 0xd7, 0x82, 0x10, 0xc1, 0x82, 0x1e, 0x4a, 0x76, 0x33, 0xb4,
	0xa1, 0x6d, 0x12, 0x37, 0xd9, 0xad, 0xfe, 0xf7, 0xb2, 0xd9, 0x2d, 0x8a, 0x05, 0x6f, 0x79, 0xbf,
	0x99, 0x09, 0x6f, 0xe6, 0xc1, 0x30, 0xdb, 0xaa, 0x9d, 0x65, 0x4e, 0x68, 0x99, 0x99, 0x0f, 0x56,
	0x4d, 0xd8, 0x5e, 0x28, 0x8f, 0x05, 0xb5, 0x85, 0xf1, 0x86, 0x9c, 0x85, 0x32, 0x6d, 0xcb, 0xb4,
	0x9a, 0xa4, 0x73, 0x38, 0x7f, 0x5c, 0x63, 0xbe, 0xe1, 0x28, 0xe4, 0x27, 0xc7, 0xf7, 0x12, 0x9d,
	0x27, 0x0f, 0x10, 0xd7, 0x63, 0x4b, 0x67, 0x31, 0x4f, 0xa2, 0x51, 0x34, 0xee, 0x4f, 0x07, 0xf4,
	0xf7, 0x28, 0x5d, 0x08, 0xe5, 0x9f, 0x2d, 0xe6, 0xbc, 0xb7, 0x6f, 0x5f, 0xe9, 0x1c, 0x7a, 0x07,
	0x4a, 0x86, 0x00, 0x12, 0x2d, 0x6a, 0xe9, 0x96, 0x46, 0x27, 0xd1, 0xe8, 0xff, 0x38, 0xe6, 0x71,
	0x4b, 0x9e, 0x34, 0xb9, 0x82, 0xd3, 0x4c, 0x69, 0xb9, 0xac, 0xcc, 0xb6, 0xdc, 0xa1, 0x4b, 0x3a,
	0xa1, 0xa1, 0x5f, 0xb3, 0x97, 0x06, 0xa5, 0x33, 0x20, 0x3f, 0xbd, 0x39, 0x6b, 0xb4, 0x43, 0x72,
	0x01, 0x27, 0x45, 0x0d, 0x82, 0xb1, 0x1e, 0x6f, 0x04, 0xb9, 0x84, 0x6e, 0x81, 0xc2, 0x19, 0x9d,
	0x74, 0x46, 0xd1, 0x38, 0xe6, 0xad, 0x9a, 0x2a, 0x80, 0x99, 0x31, 0x7e, 0x11, 0xae, 0x40, 0xde,
	0x00, 0xbe, 0x7f, 0x24, 0xd7, 0xc7, 0x3b, 0x1d, 0xdd, 0x62, 0x70, 0xf3, 0x77, 0x53, 0x63, 0x2a,
	0xfd, 0x37, 0x89, 0x66, 0xf4, 0xf5, 0x76, 0xa5, 0xfc, 0xba, 0xcc, 0x68, 0x6e, 0x76, 0x6c, 0x83,
	0x5b, 0x29, 0xee, 0x94, 0xce, 0x59, 0x13, 0x89, 0xdd, 0xac, 0x58, 0x08, 0xe1, 0x10, 0x4e, 0xd6,
	0x0d, 0xf2, 0xfe, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xd7, 0x68, 0xc0, 0xb4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BootWaiterClient is the client API for BootWaiter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BootWaiterClient interface {
	CheckReady(ctx context.Context, in *CheckReadyRequest, opts ...grpc.CallOption) (BootWaiter_CheckReadyClient, error)
}

type bootWaiterClient struct {
	cc grpc.ClientConnInterface
}

func NewBootWaiterClient(cc grpc.ClientConnInterface) BootWaiterClient {
	return &bootWaiterClient{cc}
}

func (c *bootWaiterClient) CheckReady(ctx context.Context, in *CheckReadyRequest, opts ...grpc.CallOption) (BootWaiter_CheckReadyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BootWaiter_serviceDesc.Streams[0], "/blimp.sandbox.v0.BootWaiter/CheckReady", opts...)
	if err != nil {
		return nil, err
	}
	x := &bootWaiterCheckReadyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BootWaiter_CheckReadyClient interface {
	Recv() (*CheckReadyResponse, error)
	grpc.ClientStream
}

type bootWaiterCheckReadyClient struct {
	grpc.ClientStream
}

func (x *bootWaiterCheckReadyClient) Recv() (*CheckReadyResponse, error) {
	m := new(CheckReadyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BootWaiterServer is the server API for BootWaiter service.
type BootWaiterServer interface {
	CheckReady(*CheckReadyRequest, BootWaiter_CheckReadyServer) error
}

// UnimplementedBootWaiterServer can be embedded to have forward compatible implementations.
type UnimplementedBootWaiterServer struct {
}

func (*UnimplementedBootWaiterServer) CheckReady(req *CheckReadyRequest, srv BootWaiter_CheckReadyServer) error {
	return status.Errorf(codes.Unimplemented, "method CheckReady not implemented")
}

func RegisterBootWaiterServer(s *grpc.Server, srv BootWaiterServer) {
	s.RegisterService(&_BootWaiter_serviceDesc, srv)
}

func _BootWaiter_CheckReady_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CheckReadyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BootWaiterServer).CheckReady(m, &bootWaiterCheckReadyServer{stream})
}

type BootWaiter_CheckReadyServer interface {
	Send(*CheckReadyResponse) error
	grpc.ServerStream
}

type bootWaiterCheckReadyServer struct {
	grpc.ServerStream
}

func (x *bootWaiterCheckReadyServer) Send(m *CheckReadyResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _BootWaiter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blimp.sandbox.v0.BootWaiter",
	HandlerType: (*BootWaiterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckReady",
			Handler:       _BootWaiter_CheckReady_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blimp/sandbox/v0/waiter.proto",
}
