// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blimp/sandbox/v0/waiter.proto

package sandbox

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckReadyRequest struct {
	WaitSpec             *WaitSpec `protobuf:"bytes,1,opt,name=wait_spec,json=waitSpec,proto3" json:"wait_spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CheckReadyRequest) Reset()         { *m = CheckReadyRequest{} }
func (m *CheckReadyRequest) String() string { return proto.CompactTextString(m) }
func (*CheckReadyRequest) ProtoMessage()    {}
func (*CheckReadyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_845dc80cbf17fb57, []int{0}
}

func (m *CheckReadyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckReadyRequest.Unmarshal(m, b)
}
func (m *CheckReadyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckReadyRequest.Marshal(b, m, deterministic)
}
func (m *CheckReadyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckReadyRequest.Merge(m, src)
}
func (m *CheckReadyRequest) XXX_Size() int {
	return xxx_messageInfo_CheckReadyRequest.Size(m)
}
func (m *CheckReadyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckReadyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckReadyRequest proto.InternalMessageInfo

func (m *CheckReadyRequest) GetWaitSpec() *WaitSpec {
	if m != nil {
		return m.WaitSpec
	}
	return nil
}

type WaitSpec struct {
	DependsOn            []string `protobuf:"bytes,1,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitSpec) Reset()         { *m = WaitSpec{} }
func (m *WaitSpec) String() string { return proto.CompactTextString(m) }
func (*WaitSpec) ProtoMessage()    {}
func (*WaitSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_845dc80cbf17fb57, []int{1}
}

func (m *WaitSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitSpec.Unmarshal(m, b)
}
func (m *WaitSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitSpec.Marshal(b, m, deterministic)
}
func (m *WaitSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitSpec.Merge(m, src)
}
func (m *WaitSpec) XXX_Size() int {
	return xxx_messageInfo_WaitSpec.Size(m)
}
func (m *WaitSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitSpec.DiscardUnknown(m)
}

var xxx_messageInfo_WaitSpec proto.InternalMessageInfo

func (m *WaitSpec) GetDependsOn() []string {
	if m != nil {
		return m.DependsOn
	}
	return nil
}

type CheckReadyResponse struct {
	Ready                bool     `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckReadyResponse) Reset()         { *m = CheckReadyResponse{} }
func (m *CheckReadyResponse) String() string { return proto.CompactTextString(m) }
func (*CheckReadyResponse) ProtoMessage()    {}
func (*CheckReadyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_845dc80cbf17fb57, []int{2}
}

func (m *CheckReadyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckReadyResponse.Unmarshal(m, b)
}
func (m *CheckReadyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckReadyResponse.Marshal(b, m, deterministic)
}
func (m *CheckReadyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckReadyResponse.Merge(m, src)
}
func (m *CheckReadyResponse) XXX_Size() int {
	return xxx_messageInfo_CheckReadyResponse.Size(m)
}
func (m *CheckReadyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckReadyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckReadyResponse proto.InternalMessageInfo

func (m *CheckReadyResponse) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

func init() {
	proto.RegisterType((*CheckReadyRequest)(nil), "blimp.sandbox.v0.CheckReadyRequest")
	proto.RegisterType((*WaitSpec)(nil), "blimp.sandbox.v0.WaitSpec")
	proto.RegisterType((*CheckReadyResponse)(nil), "blimp.sandbox.v0.CheckReadyResponse")
}

func init() {
	proto.RegisterFile("blimp/sandbox/v0/waiter.proto", fileDescriptor_845dc80cbf17fb57)
}

var fileDescriptor_845dc80cbf17fb57 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0x4d, 0x4b, 0x03, 0x31,
	0x14, 0x74, 0x11, 0x65, 0xf7, 0x79, 0xd1, 0xe0, 0xa1, 0x14, 0x0a, 0x65, 0xf5, 0x50, 0x45, 0x93,
	0x52, 0x0f, 0xde, 0xeb, 0x55, 0x10, 0xe2, 0xa1, 0xe8, 0xa5, 0xe4, 0xe3, 0xb1, 0x0d, 0xdb, 0x26,
	0x71, 0x93, 0xb6, 0xfa, 0xef, 0xa5, 0xd9, 0x2d, 0x8a, 0x05, 0x6f, 0x99, 0x99, 0x0c, 0xf3, 0x66,
	0x60, 0x20, 0x97, 0x66, 0xe5, 0x59, 0x10, 0x56, 0x4b, 0xf7, 0xc9, 0x36, 0x63, 0xb6, 0x15, 0x26,
	0x62, 0x43, 0x7d, 0xe3, 0xa2, 0x23, 0xe7, 0x49, 0xa6, 0x9d, 0x4c, 0x37, 0xe3, 0xf2, 0x19, 0x2e,
	0x9e, 0x16, 0xa8, 0x6a, 0x8e, 0x42, 0x7f, 0x71, 0xfc, 0x58, 0x63, 0x88, 0xe4, 0x11, 0x8a, 0x9d,
	0x6d, 0x1e, 0x3c, 0xaa, 0x5e, 0x36, 0xcc, 0x46, 0x67, 0x93, 0x3e, 0xfd, 0x6b, 0xa5, 0x33, 0x61,
	0xe2, 0xab, 0x47, 0xc5, 0xf3, 0x6d, 0xf7, 0x2a, 0x6f, 0x20, 0xdf, 0xb3, 0x64, 0x00, 0xa0, 0xd1,
	0xa3, 0xd5, 0x61, 0xee, 0x6c, 0x2f, 0x1b, 0x1e, 0x8f, 0x0a, 0x5e, 0x74, 0xcc, 0x8b, 0x2d, 0x6f,
	0x81, 0xfc, 0x0e, 0x0e, 0xde, 0xd9, 0x80, 0xe4, 0x12, 0x4e, 0x9a, 0x1d, 0x91, 0x52, 0x73, 0xde,
	0x82, 0x49, 0x05, 0x30, 0x75, 0x2e, 0xce, 0x52, 0x15, 0xf2, 0x06, 0xf0, 0xe3, 0x24, 0x57, 0x87,
	0x87, 0x1d, 0x14, 0xea, 0x5f, 0xff, 0xff, 0xa9, 0x0d, 0x2f, 0x8f, 0xa6, 0xf4, 0xfd, 0xae, 0x32,
	0x71, 0xb1, 0x96, 0x54, 0xb9, 0x15, 0xab, 0x71, 0xa9, 0xc5, 0xbd, 0xb1, 0x8a, 0xb5, 0xab, 0xfa,
	0xba, 0x62, 0x69, 0xc7, 0xfd, 0xbe, 0xf2, 0x34, 0xc1, 0x87, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x36, 0x8d, 0xe9, 0x89, 0x77, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BootWaiterClient is the client API for BootWaiter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BootWaiterClient interface {
	CheckReady(ctx context.Context, in *CheckReadyRequest, opts ...grpc.CallOption) (*CheckReadyResponse, error)
}

type bootWaiterClient struct {
	cc grpc.ClientConnInterface
}

func NewBootWaiterClient(cc grpc.ClientConnInterface) BootWaiterClient {
	return &bootWaiterClient{cc}
}

func (c *bootWaiterClient) CheckReady(ctx context.Context, in *CheckReadyRequest, opts ...grpc.CallOption) (*CheckReadyResponse, error) {
	out := new(CheckReadyResponse)
	err := c.cc.Invoke(ctx, "/blimp.sandbox.v0.BootWaiter/CheckReady", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BootWaiterServer is the server API for BootWaiter service.
type BootWaiterServer interface {
	CheckReady(context.Context, *CheckReadyRequest) (*CheckReadyResponse, error)
}

// UnimplementedBootWaiterServer can be embedded to have forward compatible implementations.
type UnimplementedBootWaiterServer struct {
}

func (*UnimplementedBootWaiterServer) CheckReady(ctx context.Context, req *CheckReadyRequest) (*CheckReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckReady not implemented")
}

func RegisterBootWaiterServer(s *grpc.Server, srv BootWaiterServer) {
	s.RegisterService(&_BootWaiter_serviceDesc, srv)
}

func _BootWaiter_CheckReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootWaiterServer).CheckReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blimp.sandbox.v0.BootWaiter/CheckReady",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootWaiterServer).CheckReady(ctx, req.(*CheckReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BootWaiter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blimp.sandbox.v0.BootWaiter",
	HandlerType: (*BootWaiterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckReady",
			Handler:    _BootWaiter_CheckReady_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blimp/sandbox/v0/waiter.proto",
}
