// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kelda-inc/blimp/_proto/blimp/wait/v0/wait.proto

package wait

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	errors "github.com/kelda/blimp/pkg/proto/errors"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckReadyRequest struct {
	Namespace            string    `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WaitSpec             *WaitSpec `protobuf:"bytes,2,opt,name=wait_spec,json=waitSpec,proto3" json:"wait_spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CheckReadyRequest) Reset()         { *m = CheckReadyRequest{} }
func (m *CheckReadyRequest) String() string { return proto.CompactTextString(m) }
func (*CheckReadyRequest) ProtoMessage()    {}
func (*CheckReadyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3bf768fc7560e3, []int{0}
}

func (m *CheckReadyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckReadyRequest.Unmarshal(m, b)
}
func (m *CheckReadyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckReadyRequest.Marshal(b, m, deterministic)
}
func (m *CheckReadyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckReadyRequest.Merge(m, src)
}
func (m *CheckReadyRequest) XXX_Size() int {
	return xxx_messageInfo_CheckReadyRequest.Size(m)
}
func (m *CheckReadyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckReadyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckReadyRequest proto.InternalMessageInfo

func (m *CheckReadyRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CheckReadyRequest) GetWaitSpec() *WaitSpec {
	if m != nil {
		return m.WaitSpec
	}
	return nil
}

type WaitSpec struct {
	// depends_on is a list of services that must be running or healthy
	// before the service can start.
	DependsOn []*ServiceCondition `protobuf:"bytes,1,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	// bind_volumes is a list of paths that must be fully synced before the
	// service can start.
	BindVolumes []string `protobuf:"bytes,2,rep,name=bind_volumes,json=bindVolumes,proto3" json:"bind_volumes,omitempty"`
	// finished_volume_init is a list of services that must have finished initializing
	// volumes before the service can start.
	FinishedVolumeInit   []string `protobuf:"bytes,3,rep,name=finished_volume_init,json=finishedVolumeInit,proto3" json:"finished_volume_init,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitSpec) Reset()         { *m = WaitSpec{} }
func (m *WaitSpec) String() string { return proto.CompactTextString(m) }
func (*WaitSpec) ProtoMessage()    {}
func (*WaitSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3bf768fc7560e3, []int{1}
}

func (m *WaitSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitSpec.Unmarshal(m, b)
}
func (m *WaitSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitSpec.Marshal(b, m, deterministic)
}
func (m *WaitSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitSpec.Merge(m, src)
}
func (m *WaitSpec) XXX_Size() int {
	return xxx_messageInfo_WaitSpec.Size(m)
}
func (m *WaitSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitSpec.DiscardUnknown(m)
}

var xxx_messageInfo_WaitSpec proto.InternalMessageInfo

func (m *WaitSpec) GetDependsOn() []*ServiceCondition {
	if m != nil {
		return m.DependsOn
	}
	return nil
}

func (m *WaitSpec) GetBindVolumes() []string {
	if m != nil {
		return m.BindVolumes
	}
	return nil
}

func (m *WaitSpec) GetFinishedVolumeInit() []string {
	if m != nil {
		return m.FinishedVolumeInit
	}
	return nil
}

type ServiceCondition struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Condition            string   `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceCondition) Reset()         { *m = ServiceCondition{} }
func (m *ServiceCondition) String() string { return proto.CompactTextString(m) }
func (*ServiceCondition) ProtoMessage()    {}
func (*ServiceCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3bf768fc7560e3, []int{2}
}

func (m *ServiceCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceCondition.Unmarshal(m, b)
}
func (m *ServiceCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceCondition.Marshal(b, m, deterministic)
}
func (m *ServiceCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceCondition.Merge(m, src)
}
func (m *ServiceCondition) XXX_Size() int {
	return xxx_messageInfo_ServiceCondition.Size(m)
}
func (m *ServiceCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceCondition.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceCondition proto.InternalMessageInfo

func (m *ServiceCondition) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ServiceCondition) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type CheckReadyResponse struct {
	Error *errors.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Ready bool          `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	// An optional message providing more information on why the container
	// needs to wait.
	Reason               string   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckReadyResponse) Reset()         { *m = CheckReadyResponse{} }
func (m *CheckReadyResponse) String() string { return proto.CompactTextString(m) }
func (*CheckReadyResponse) ProtoMessage()    {}
func (*CheckReadyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3bf768fc7560e3, []int{3}
}

func (m *CheckReadyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckReadyResponse.Unmarshal(m, b)
}
func (m *CheckReadyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckReadyResponse.Marshal(b, m, deterministic)
}
func (m *CheckReadyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckReadyResponse.Merge(m, src)
}
func (m *CheckReadyResponse) XXX_Size() int {
	return xxx_messageInfo_CheckReadyResponse.Size(m)
}
func (m *CheckReadyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckReadyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckReadyResponse proto.InternalMessageInfo

func (m *CheckReadyResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *CheckReadyResponse) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

func (m *CheckReadyResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckReadyRequest)(nil), "blimp.wait.v0.CheckReadyRequest")
	proto.RegisterType((*WaitSpec)(nil), "blimp.wait.v0.WaitSpec")
	proto.RegisterType((*ServiceCondition)(nil), "blimp.wait.v0.ServiceCondition")
	proto.RegisterType((*CheckReadyResponse)(nil), "blimp.wait.v0.CheckReadyResponse")
}

func init() {
	proto.RegisterFile("github.com/kelda-inc/blimp/_proto/blimp/wait/v0/wait.proto", fileDescriptor_fc3bf768fc7560e3)
}

var fileDescriptor_fc3bf768fc7560e3 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x25, 0x5d, 0xb5, 0x6c, 0x66, 0x41, 0x02, 0xab, 0x2a, 0x51, 0x85, 0x44, 0x9a, 0xd3, 0x22,
	0x20, 0x89, 0x02, 0x27, 0x0e, 0x1c, 0x5a, 0x71, 0x80, 0x0b, 0x92, 0x2b, 0x40, 0xe2, 0x12, 0x25,
	0xce, 0xb0, 0x6b, 0xed, 0xc6, 0x36, 0xb6, 0x37, 0x15, 0x5f, 0xc3, 0xaf, 0x22, 0xdb, 0x89, 0x16,
	0xb6, 0x55, 0x4f, 0x99, 0x79, 0xf3, 0xfc, 0x9e, 0xf3, 0x3c, 0xf0, 0x7e, 0xc5, 0xed, 0x7a, 0xd7,
	0xe6, 0x4c, 0xf6, 0xc5, 0x06, 0xb7, 0x5d, 0xf3, 0x86, 0x0b, 0x56, 0xb4, 0x5b, 0xde, 0xab, 0xa2,
	0x56, 0x5a, 0x5a, 0x39, 0x36, 0x37, 0x0d, 0xb7, 0xc5, 0x50, 0xfa, 0x6f, 0xee, 0x07, 0xe4, 0xb1,
	0x9f, 0xe4, 0x1e, 0x19, 0xca, 0xf3, 0x5b, 0x52, 0x77, 0xc9, 0xa0, 0xd6, 0x52, 0x1b, 0x27, 0x14,
	0xaa, 0x20, 0x95, 0xad, 0xe0, 0xe9, 0xd5, 0x1a, 0xd9, 0x86, 0x62, 0xd3, 0xfd, 0xa6, 0xf8, 0x6b,
	0x87, 0xc6, 0x92, 0xe7, 0x10, 0x8b, 0xa6, 0x47, 0xa3, 0x1a, 0x86, 0x49, 0x94, 0x46, 0xcb, 0x98,
	0xee, 0x01, 0xf2, 0x0e, 0x62, 0xe7, 0x5c, 0x1b, 0x85, 0x2c, 0x39, 0x4a, 0xa3, 0xe5, 0xa2, 0x7a,
	0x96, 0xff, 0x77, 0xa3, 0xfc, 0x7b, 0xc3, 0xed, 0xb5, 0x42, 0x46, 0xe7, 0x37, 0x63, 0x95, 0xfd,
	0x89, 0x60, 0x3e, 0xc1, 0xe4, 0x03, 0x40, 0x87, 0x0a, 0x45, 0x67, 0x6a, 0x29, 0x92, 0x28, 0x9d,
	0x2d, 0x17, 0xd5, 0x8b, 0x03, 0x8d, 0x6b, 0xd4, 0x03, 0x67, 0x78, 0x25, 0x45, 0xc7, 0x2d, 0x97,
	0x82, 0xc6, 0xe3, 0x91, 0x2f, 0x82, 0x5c, 0xc0, 0xa3, 0x96, 0x8b, 0xae, 0x1e, 0xe4, 0x76, 0xd7,
	0xa3, 0x49, 0x8e, 0xd2, 0xd9, 0x32, 0xa6, 0x0b, 0x87, 0x7d, 0x0b, 0x10, 0x29, 0xe1, 0xf4, 0x27,
	0x17, 0xdc, 0xac, 0x71, 0xa2, 0xd5, 0x5c, 0x70, 0x9b, 0xcc, 0x3c, 0x95, 0x4c, 0xb3, 0x40, 0xff,
	0x24, 0xb8, 0xcd, 0x3e, 0xc3, 0x93, 0x43, 0x4f, 0x92, 0xc0, 0x43, 0x13, 0xb0, 0x31, 0x87, 0xa9,
	0x75, 0x19, 0xb1, 0x89, 0xe6, 0x53, 0x88, 0xe9, 0x1e, 0xc8, 0x14, 0x90, 0x7f, 0x63, 0x35, 0x4a,
	0x0a, 0x83, 0xe4, 0x35, 0x1c, 0xfb, 0xf0, 0xbd, 0xd6, 0xa2, 0x3a, 0x1b, 0xff, 0x78, 0x7c, 0x90,
	0xa1, 0xcc, 0x3f, 0xba, 0x8a, 0x06, 0x12, 0x39, 0x85, 0x63, 0xed, 0x8e, 0x7b, 0xf5, 0x39, 0x0d,
	0x0d, 0x39, 0x83, 0x13, 0x8d, 0x8d, 0x91, 0x22, 0x99, 0x79, 0xd3, 0xb1, 0xab, 0x18, 0xc0, 0xa5,
	0x94, 0xd6, 0x45, 0x8c, 0x9a, 0x7c, 0x05, 0xd8, 0xfb, 0x93, 0xf4, 0x20, 0xda, 0x5b, 0x2f, 0x7e,
	0x7e, 0x71, 0x0f, 0x23, 0x5c, 0x3e, 0x7b, 0x50, 0x46, 0x97, 0xaf, 0x7e, 0xbc, 0xbc, 0x67, 0x6d,
	0xd5, 0x66, 0x55, 0x84, 0x95, 0x73, 0x32, 0xed, 0x89, 0xaf, 0xdf, 0xfe, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0x77, 0x27, 0xe7, 0x3c, 0xea, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BootWaiterClient is the client API for BootWaiter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BootWaiterClient interface {
	CheckReady(ctx context.Context, in *CheckReadyRequest, opts ...grpc.CallOption) (BootWaiter_CheckReadyClient, error)
}

type bootWaiterClient struct {
	cc grpc.ClientConnInterface
}

func NewBootWaiterClient(cc grpc.ClientConnInterface) BootWaiterClient {
	return &bootWaiterClient{cc}
}

func (c *bootWaiterClient) CheckReady(ctx context.Context, in *CheckReadyRequest, opts ...grpc.CallOption) (BootWaiter_CheckReadyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BootWaiter_serviceDesc.Streams[0], "/blimp.wait.v0.BootWaiter/CheckReady", opts...)
	if err != nil {
		return nil, err
	}
	x := &bootWaiterCheckReadyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BootWaiter_CheckReadyClient interface {
	Recv() (*CheckReadyResponse, error)
	grpc.ClientStream
}

type bootWaiterCheckReadyClient struct {
	grpc.ClientStream
}

func (x *bootWaiterCheckReadyClient) Recv() (*CheckReadyResponse, error) {
	m := new(CheckReadyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BootWaiterServer is the server API for BootWaiter service.
type BootWaiterServer interface {
	CheckReady(*CheckReadyRequest, BootWaiter_CheckReadyServer) error
}

// UnimplementedBootWaiterServer can be embedded to have forward compatible implementations.
type UnimplementedBootWaiterServer struct {
}

func (*UnimplementedBootWaiterServer) CheckReady(req *CheckReadyRequest, srv BootWaiter_CheckReadyServer) error {
	return status.Errorf(codes.Unimplemented, "method CheckReady not implemented")
}

func RegisterBootWaiterServer(s *grpc.Server, srv BootWaiterServer) {
	s.RegisterService(&_BootWaiter_serviceDesc, srv)
}

func _BootWaiter_CheckReady_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CheckReadyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BootWaiterServer).CheckReady(m, &bootWaiterCheckReadyServer{stream})
}

type BootWaiter_CheckReadyServer interface {
	Send(*CheckReadyResponse) error
	grpc.ServerStream
}

type bootWaiterCheckReadyServer struct {
	grpc.ServerStream
}

func (x *bootWaiterCheckReadyServer) Send(m *CheckReadyResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _BootWaiter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blimp.wait.v0.BootWaiter",
	HandlerType: (*BootWaiterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckReady",
			Handler:       _BootWaiter_CheckReady_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/kelda-inc/blimp/_proto/blimp/wait/v0/wait.proto",
}
