// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blimp/login/v0/login.proto

package login

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	errors "github.com/kelda/blimp/pkg/proto/errors"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fddd5c19a272a170, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

type LoginResponse struct {
	Error *errors.Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Msg:
	//	*LoginResponse_Instructions
	//	*LoginResponse_Result
	Msg                  isLoginResponse_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fddd5c19a272a170, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetError() *errors.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type isLoginResponse_Msg interface {
	isLoginResponse_Msg()
}

type LoginResponse_Instructions struct {
	Instructions *LoginInstructions `protobuf:"bytes,2,opt,name=instructions,proto3,oneof"`
}

type LoginResponse_Result struct {
	Result *LoginResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*LoginResponse_Instructions) isLoginResponse_Msg() {}

func (*LoginResponse_Result) isLoginResponse_Msg() {}

func (m *LoginResponse) GetMsg() isLoginResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *LoginResponse) GetInstructions() *LoginInstructions {
	if x, ok := m.GetMsg().(*LoginResponse_Instructions); ok {
		return x.Instructions
	}
	return nil
}

func (m *LoginResponse) GetResult() *LoginResult {
	if x, ok := m.GetMsg().(*LoginResponse_Result); ok {
		return x.Result
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LoginResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LoginResponse_Instructions)(nil),
		(*LoginResponse_Result)(nil),
	}
}

type LoginInstructions struct {
	URL                  string   `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginInstructions) Reset()         { *m = LoginInstructions{} }
func (m *LoginInstructions) String() string { return proto.CompactTextString(m) }
func (*LoginInstructions) ProtoMessage()    {}
func (*LoginInstructions) Descriptor() ([]byte, []int) {
	return fileDescriptor_fddd5c19a272a170, []int{2}
}

func (m *LoginInstructions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInstructions.Unmarshal(m, b)
}
func (m *LoginInstructions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInstructions.Marshal(b, m, deterministic)
}
func (m *LoginInstructions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInstructions.Merge(m, src)
}
func (m *LoginInstructions) XXX_Size() int {
	return xxx_messageInfo_LoginInstructions.Size(m)
}
func (m *LoginInstructions) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInstructions.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInstructions proto.InternalMessageInfo

func (m *LoginInstructions) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type LoginResult struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResult) Reset()         { *m = LoginResult{} }
func (m *LoginResult) String() string { return proto.CompactTextString(m) }
func (*LoginResult) ProtoMessage()    {}
func (*LoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fddd5c19a272a170, []int{3}
}

func (m *LoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResult.Unmarshal(m, b)
}
func (m *LoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResult.Marshal(b, m, deterministic)
}
func (m *LoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResult.Merge(m, src)
}
func (m *LoginResult) XXX_Size() int {
	return xxx_messageInfo_LoginResult.Size(m)
}
func (m *LoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResult proto.InternalMessageInfo

func (m *LoginResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "blimp.login.v0.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "blimp.login.v0.LoginResponse")
	proto.RegisterType((*LoginInstructions)(nil), "blimp.login.v0.LoginInstructions")
	proto.RegisterType((*LoginResult)(nil), "blimp.login.v0.LoginResult")
}

func init() {
	proto.RegisterFile("blimp/login/v0/login.proto", fileDescriptor_fddd5c19a272a170)
}

var fileDescriptor_fddd5c19a272a170 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x9b, 0x86, 0x14, 0xde, 0x69, 0xdf, 0xa2, 0x8b, 0x48, 0x88, 0x15, 0x34, 0xa0, 0xf4,
	0x20, 0x9b, 0x50, 0xf1, 0xe0, 0xb5, 0x20, 0x46, 0xe8, 0xc5, 0x05, 0x2f, 0xde, 0x4c, 0x5d, 0x62,
	0xc8, 0x9f, 0x8d, 0xbb, 0x9b, 0x7c, 0x42, 0x3f, 0x98, 0x64, 0x26, 0x42, 0x8b, 0xf6, 0xf6, 0xcc,
	0xe4, 0xf7, 0x3c, 0x3b, 0x99, 0x81, 0x20, 0x2d, 0xf3, 0xaa, 0x89, 0x4a, 0x95, 0xe5, 0x75, 0xd4,
	0xc5, 0x24, 0x78, 0xa3, 0x95, 0x55, 0x6c, 0x8e, 0xdf, 0x38, 0xb5, 0xba, 0x38, 0x58, 0x10, 0x2b,
	0xb5, 0x56, 0xda, 0xf4, 0x30, 0x29, 0xa2, 0xc3, 0x39, 0xcc, 0x36, 0x3d, 0x29, 0xe4, 0x67, 0x2b,
	0x8d, 0x0d, 0xbf, 0x1c, 0xf8, 0x3f, 0x34, 0x4c, 0xa3, 0x6a, 0x23, 0xd9, 0x0d, 0x78, 0xe8, 0xf0,
	0x9d, 0x0b, 0x67, 0x39, 0x5d, 0x9d, 0x72, 0xca, 0x1f, 0x52, 0xba, 0x98, 0x3f, 0xf4, 0x4a, 0x10,
	0xc4, 0x1e, 0x61, 0x96, 0xd7, 0xc6, 0xea, 0x76, 0x6b, 0x73, 0x55, 0x1b, 0x7f, 0x8c, 0xa6, 0x4b,
	0xbe, 0x3f, 0x14, 0xc7, 0x27, 0x9e, 0x76, 0xc0, 0x64, 0x24, 0xf6, 0x8c, 0xec, 0x0e, 0x26, 0x5a,
	0x9a, 0xb6, 0xb4, 0xbe, 0x8b, 0x11, 0x67, 0x7f, 0x46, 0x08, 0x44, 0x92, 0x91, 0x18, 0xe0, 0xb5,
	0x07, 0x6e, 0x65, 0xb2, 0xf0, 0x0a, 0x8e, 0x7f, 0x3d, 0xc1, 0x8e, 0xc0, 0x7d, 0x11, 0x1b, 0xfc,
	0x8f, 0x7f, 0xa2, 0x97, 0xe1, 0x3d, 0x4c, 0x77, 0x62, 0xd8, 0x09, 0x78, 0x56, 0x15, 0xb2, 0x1e,
	0x10, 0x2a, 0xfa, 0x2e, 0x2d, 0x60, 0x4c, 0x5d, 0x2c, 0x56, 0xcf, 0xe0, 0xa1, 0x95, 0x25, 0x3f,
	0x62, 0x71, 0x60, 0x42, 0x5c, 0x6c, 0x70, 0x7e, 0x68, 0x7e, 0xdc, 0x72, 0x38, 0x8a, 0x9d, 0xf5,
	0xf2, 0xf5, 0x3a, 0xcb, 0xed, 0x47, 0x9b, 0xf2, 0xad, 0xaa, 0xa2, 0x42, 0x96, 0xef, 0x6f, 0x11,
	0x1d, 0xaf, 0x29, 0xb2, 0x08, 0xef, 0x45, 0x97, 0x4e, 0x27, 0x58, 0xdc, 0x7e, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x41, 0x4a, 0x79, 0x62, 0x08, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LoginClient is the client API for Login service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (Login_LoginClient, error)
}

type loginClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginClient(cc grpc.ClientConnInterface) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (Login_LoginClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Login_serviceDesc.Streams[0], "/blimp.login.v0.Login/Login", opts...)
	if err != nil {
		return nil, err
	}
	x := &loginLoginClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Login_LoginClient interface {
	Recv() (*LoginResponse, error)
	grpc.ClientStream
}

type loginLoginClient struct {
	grpc.ClientStream
}

func (x *loginLoginClient) Recv() (*LoginResponse, error) {
	m := new(LoginResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LoginServer is the server API for Login service.
type LoginServer interface {
	Login(*LoginRequest, Login_LoginServer) error
}

// UnimplementedLoginServer can be embedded to have forward compatible implementations.
type UnimplementedLoginServer struct {
}

func (*UnimplementedLoginServer) Login(req *LoginRequest, srv Login_LoginServer) error {
	return status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterLoginServer(s *grpc.Server, srv LoginServer) {
	s.RegisterService(&_Login_serviceDesc, srv)
}

func _Login_Login_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoginRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoginServer).Login(m, &loginLoginServer{stream})
}

type Login_LoginServer interface {
	Send(*LoginResponse) error
	grpc.ServerStream
}

type loginLoginServer struct {
	grpc.ServerStream
}

func (x *loginLoginServer) Send(m *LoginResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Login_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blimp.login.v0.Login",
	HandlerType: (*LoginServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Login",
			Handler:       _Login_Login_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blimp/login/v0/login.proto",
}
